// GENERATED FILE — do not edit by hand.
// Regenerate together with client/src/data/validAlts.generated.ts — see
// the comment atop scripts/generate-valid-alts.ts for the exact command.
//
// Minimal, server-safe mirror of client/src/data/algSets.ts: just enough
// (id/puzzle/caseIds, case moves, and the same validated alts as the
// client Trainer uses) for the server to build an algorithm-set Battle
// round scramble without depending on client-only code.

export const ALG_SET_INDEX = [
  {
    "id": "OLL",
    "puzzle": "333",
    "caseIds": [
      "OLL1",
      "OLL2",
      "OLL3",
      "OLL4",
      "OLL5",
      "OLL6",
      "OLL7",
      "OLL8",
      "OLL9",
      "OLL10",
      "OLL11",
      "OLL12",
      "OLL13",
      "OLL14",
      "OLL15",
      "OLL16",
      "OLL17",
      "OLL18",
      "OLL19",
      "OLL20",
      "OLL21",
      "OLL22",
      "OLL23",
      "OLL24",
      "OLL25",
      "OLL26",
      "OLL27",
      "OLL28",
      "OLL29",
      "OLL30",
      "OLL31",
      "OLL32",
      "OLL33",
      "OLL34",
      "OLL35",
      "OLL36",
      "OLL37",
      "OLL38",
      "OLL39",
      "OLL40",
      "OLL41",
      "OLL42",
      "OLL43",
      "OLL44",
      "OLL45",
      "OLL46",
      "OLL47",
      "OLL48",
      "OLL49",
      "OLL50",
      "OLL51",
      "OLL52",
      "OLL53",
      "OLL54",
      "OLL55",
      "OLL56",
      "OLL57"
    ]
  },
  {
    "id": "PLL",
    "puzzle": "333",
    "caseIds": [
      "Ua",
      "Ub",
      "Z",
      "H",
      "Aa",
      "Ab",
      "E",
      "T",
      "F",
      "Ja",
      "Jb",
      "Ra",
      "Rb",
      "Ga",
      "Gb",
      "Gc",
      "Gd",
      "V",
      "Y",
      "Na",
      "Nb"
    ]
  },
  {
    "id": "F2L",
    "puzzle": "333",
    "caseIds": [
      "F2L1",
      "F2L2",
      "F2L3",
      "F2L4",
      "F2L5",
      "F2L6",
      "F2L7",
      "F2L8",
      "F2L9",
      "F2L10",
      "F2L19",
      "F2L20",
      "F2L21",
      "F2L22",
      "F2L11",
      "F2L12",
      "F2L13",
      "F2L14",
      "F2L15",
      "F2L16",
      "F2L17",
      "F2L18",
      "F2L23",
      "F2L24",
      "F2L25",
      "F2L26",
      "F2L27",
      "F2L28",
      "F2L29",
      "F2L30",
      "F2L31",
      "F2L32",
      "F2L33",
      "F2L34",
      "F2L35",
      "F2L36",
      "F2L37",
      "F2L38",
      "F2L39",
      "F2L40",
      "F2L41"
    ]
  },
  {
    "id": "COLL",
    "puzzle": "333",
    "caseIds": [
      "COLL-A1",
      "COLL-A2",
      "COLL-A3",
      "COLL-A4",
      "COLL-A5",
      "COLL-A6",
      "COLL-S1",
      "COLL-S2",
      "COLL-S3",
      "COLL-S4",
      "COLL-S5",
      "COLL-S6",
      "COLL-L1",
      "COLL-L2",
      "COLL-L3",
      "COLL-L4",
      "COLL-L5",
      "COLL-L6",
      "COLL-U1",
      "COLL-U2",
      "COLL-U3",
      "COLL-U4",
      "COLL-U5",
      "COLL-U6",
      "COLL-T1",
      "COLL-T2",
      "COLL-T3",
      "COLL-T4",
      "COLL-T5",
      "COLL-T6",
      "COLL-P1",
      "COLL-P2",
      "COLL-P3",
      "COLL-P4",
      "COLL-P5",
      "COLL-P6",
      "COLL-H1",
      "COLL-H2",
      "COLL-H3",
      "COLL-H4"
    ]
  },
  {
    "id": "OrtegaOLL",
    "puzzle": "222",
    "caseIds": [
      "2x2-oll-sune",
      "2x2-oll-anti-sune",
      "2x2-oll-pi",
      "2x2-oll-p",
      "2x2-oll-l",
      "2x2-oll-t",
      "2x2-oll-h"
    ]
  },
  {
    "id": "OrtegaPBL",
    "puzzle": "222",
    "caseIds": [
      "2x2-pbl-adj",
      "2x2-pbl-opp",
      "2x2-pbl-opp-opp",
      "2x2-pbl-adj-adj",
      "2x2-pbl-adj-opp",
      "2x2-pbl-opp-adj"
    ]
  },
  {
    "id": "CLL",
    "puzzle": "222",
    "caseIds": [
      "CLL-AS-1",
      "CLL-AS-2",
      "CLL-AS-3",
      "CLL-AS-4",
      "CLL-AS-5",
      "CLL-AS-6",
      "CLL-H-1",
      "CLL-H-2",
      "CLL-H-3",
      "CLL-H-4",
      "CLL-L-1",
      "CLL-L-2",
      "CLL-L-3",
      "CLL-L-4",
      "CLL-L-5",
      "CLL-L-6",
      "CLL-Pi-1",
      "CLL-Pi-2",
      "CLL-Pi-3",
      "CLL-Pi-4",
      "CLL-Pi-5",
      "CLL-Pi-6",
      "CLL-Sune-1",
      "CLL-Sune-2",
      "CLL-Sune-3",
      "CLL-Sune-4",
      "CLL-Sune-5",
      "CLL-Sune-6",
      "CLL-T-1",
      "CLL-T-2",
      "CLL-T-3",
      "CLL-T-4",
      "CLL-T-5",
      "CLL-T-6",
      "CLL-U-1",
      "CLL-U-2",
      "CLL-U-3",
      "CLL-U-4",
      "CLL-U-5",
      "CLL-U-6"
    ]
  },
  {
    "id": "EG1",
    "puzzle": "222",
    "caseIds": [
      "EG1-AS-1",
      "EG1-AS-2",
      "EG1-AS-3",
      "EG1-AS-4",
      "EG1-AS-5",
      "EG1-AS-6",
      "EG1-H-1",
      "EG1-H-2",
      "EG1-H-3",
      "EG1-H-4",
      "EG1-L-1",
      "EG1-L-2",
      "EG1-L-3",
      "EG1-L-4",
      "EG1-L-5",
      "EG1-L-6",
      "EG1-Pi-1",
      "EG1-Pi-2",
      "EG1-Pi-3",
      "EG1-Pi-4",
      "EG1-Pi-5",
      "EG1-Pi-6",
      "EG1-S-1",
      "EG1-S-2",
      "EG1-S-3",
      "EG1-S-4",
      "EG1-S-5",
      "EG1-S-6",
      "EG1-T-1",
      "EG1-T-2",
      "EG1-T-3",
      "EG1-T-4",
      "EG1-T-5",
      "EG1-T-6",
      "EG1-U-1",
      "EG1-U-2",
      "EG1-U-3",
      "EG1-U-4",
      "EG1-U-5",
      "EG1-U-6"
    ]
  },
  {
    "id": "EG2",
    "puzzle": "222",
    "caseIds": [
      "EG2-AS-1",
      "EG2-AS-2",
      "EG2-AS-3",
      "EG2-AS-4",
      "EG2-AS-5",
      "EG2-AS-6",
      "EG2-H-1",
      "EG2-H-2",
      "EG2-H-3",
      "EG2-H-4",
      "EG2-L-1",
      "EG2-L-2",
      "EG2-L-3",
      "EG2-L-4",
      "EG2-L-5",
      "EG2-L-6",
      "EG2-Pi-1",
      "EG2-Pi-2",
      "EG2-Pi-3",
      "EG2-Pi-4",
      "EG2-Pi-5",
      "EG2-Pi-6",
      "EG2-S-1",
      "EG2-S-2",
      "EG2-S-3",
      "EG2-S-4",
      "EG2-S-5",
      "EG2-S-6",
      "EG2-T-1",
      "EG2-T-2",
      "EG2-T-3",
      "EG2-T-4",
      "EG2-T-5",
      "EG2-T-6",
      "EG2-U-1",
      "EG2-U-2",
      "EG2-U-3",
      "EG2-U-4",
      "EG2-U-5",
      "EG2-U-6"
    ]
  }
] as const;

export const ALG_CASE_MOVES: Record<string, string> = {
  "OLL1": "R U2 R2 F R F' U2 R' F R F'",
  "OLL2": "y' R U' R2 D' r U r' D R2 U R'",
  "OLL3": "y' f R U R' U' f' U' F R U R' U' F'",
  "OLL4": "y' R' F2 R2 U2 R' F' R U2 R2 F2 R",
  "OLL5": "r' U2 R U R' U r",
  "OLL6": "r U2 R' U' R U' r'",
  "OLL7": "r U R' U R U2 r'",
  "OLL8": "y2 r' U' R U' R' U2 r",
  "OLL9": "y R U R' U' R' F R2 U R' U' F'",
  "OLL10": "R U R' U R' F R F' R U2 R'",
  "OLL11": "r' R2 U R' U R U2 R' U M'",
  "OLL12": "y' M' R' U' R U' R' U2 R U' M",
  "OLL13": "F U R U2 R' U' R U R' F'",
  "OLL14": "R' F R U R' F' R F U' F'",
  "OLL15": "r' U' r R' U' R U r' U r",
  "OLL16": "r U r' R U R' U' r U' r'",
  "OLL17": "R U R' U R' F R F' U2 R' F R F'",
  "OLL18": "y R U2 R2 F R F' U2 M' U R U' r'",
  "OLL19": "y S' R U R' S U' R' F R F'",
  "OLL20": "r U R' U' M2 U R U' R' U' M'",
  "OLL21": "R U R' U R U' R' U R U2 R'",
  "OLL22": "R U2 R2 U' R2 U' R2 U2 R",
  "OLL23": "R2 D R' U2 R D' R' U2 R'",
  "OLL24": "r U R' U' r' F R F'",
  "OLL25": "R U2 R D R' U2 R D' R2",
  "OLL26": "y R U2 R' U' R U' R'",
  "OLL27": "R U R' U R U2 R'",
  "OLL28": "r U R' U' M U R U' R'",
  "OLL29": "r2 D' r U r' D r2 U' r' U' r",
  "OLL30": "y' r' D' r U' r' D r2 U' r' U r U r'",
  "OLL31": "R' U' F U R U' R' F' R",
  "OLL32": "S R U R' U' R' F R f'",
  "OLL33": "R U R' U' R' F R F'",
  "OLL34": "y f R f' U' r' U' R U M'",
  "OLL35": "R U2 R2 F R F' R U2 R'",
  "OLL36": "y R U R2 F' U' F U R2 U2 R'",
  "OLL37": "F R' F' R U R U' R'",
  "OLL38": "R U R' U R U' R' U' R' F R F'",
  "OLL39": "y' f' r U r' U' r' F r S",
  "OLL40": "y R' F R U R' U' F' U R",
  "OLL41": "y2 R U R' U R U2 R' F R U R' U' F'",
  "OLL42": "R' U' R U' R' U2 R F R U R' U' F'",
  "OLL43": "y R' U' F' U F R",
  "OLL44": "f R U R' U' f'",
  "OLL45": "F R U R' U' F'",
  "OLL46": "R' U' R' F R F' U R",
  "OLL47": "y' F R' F' R U2 R U' R' U R U2 R'",
  "OLL48": "F R U R' U' R U R' U' F'",
  "OLL49": "y2 r U' r2 U r2 U r2 U' r",
  "OLL50": "r' U r2 U' r2 U' r2 U r'",
  "OLL51": "y2 F U R U' R' U R U' R' F'",
  "OLL52": "y2 R' F' U' F U' R U R' U R",
  "OLL53": "r' U' R U' R' U R U' R' U2 r",
  "OLL54": "r U R' U R U' R' U R U2 r'",
  "OLL55": "y R' F U R U' R2 F' R2 U R' U' R",
  "OLL56": "r U r' U R U' R' U R U' R' r U' r'",
  "OLL57": "R U R' U' M' U R U' r'",
  "Ua": "y2 M2 U M U2 M' U M2",
  "Ub": "y2 M2 U' M U2 M' U' M2",
  "Z": "M' U' M2 U' M2 U' M' U2 M2",
  "H": "M2 U' M2 U2 M2 U' M2",
  "Aa": "x R' U R' D2 R U' R' D2 R2 x'",
  "Ab": "x R2 D2 R U R' D2 R U' R x'",
  "E": "y x' R U' R' D R U R' D' R U R' D R U' R' D' x",
  "T": "R U R' U' R' F R2 U' R' U' R U R' F'",
  "F": "y R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
  "Ja": "y2 x R2 F R F' R U2 r' U r U2 x'",
  "Jb": "R U R' F' R U R' U' R' F R2 U' R'",
  "Ra": "y R U' R' U' R U R D R' U' R D' R' U2 R'",
  "Rb": "R' U2 R U2 R' F R U R' U' R' F' R2",
  "Ga": "R2 U R' U R' U' R U' R2 D U' R' U R D'",
  "Gb": "D R' U' R U D' R2 U R' U R U' R U' R2",
  "Gc": "R2 U' R U' R U R' U R2 D' U R U' R' D",
  "Gd": "R U R' U' D R2 U' R U' R' U R' U R2 D'",
  "V": "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2",
  "Y": "F R U' R' U' R U R' F' R U R' U' R' F R F'",
  "Na": "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
  "Nb": "R' U R U' R' F' U' F R U R' F R' F' R U' R",
  "F2L1": "U R U' R'",
  "F2L2": "F R' F' R",
  "F2L3": "F' U' F",
  "F2L4": "R U R'",
  "F2L5": "U' R U R' U2 R U' R'",
  "F2L6": "U' r U' R' U R U r'",
  "F2L7": "U' R U2 R' U' R U2 R'",
  "F2L8": "d R' U2 R U R' U2 R",
  "F2L9": "U' R U' R' U F' U' F",
  "F2L10": "U' R U R' U R U R'",
  "F2L19": "U R U2 R' U R U' R'",
  "F2L20": "y' U' R' U2 R U' R' U R",
  "F2L21": "U2 R U R' U R U' R'",
  "F2L22": "r U' r' U2 r U r'",
  "F2L11": "U' R U2 R' U F' U' F",
  "F2L12": "R U' R' U R U' R' U2 R U' R'",
  "F2L13": "y' U R' U R U' R' U' R",
  "F2L14": "U' R U' R' U R U R'",
  "F2L15": "R' D' R U' R' D R U R U' R'",
  "F2L16": "R U' R' U2 F' U' F",
  "F2L17": "R U2 R' U' R U R'",
  "F2L18": "y' R' U2 R U R' U' R",
  "F2L23": "U R U' R' U' R U' R' U R U' R'",
  "F2L24": "F U R U' R' F' R U' R'",
  "F2L25": "U' R' F R F' R U R'",
  "F2L26": "U R U' R' F R' F' R",
  "F2L27": "R U' R' U R U' R'",
  "F2L28": "R U R' U' F R' F' R",
  "F2L29": "R' F R F' U R U' R'",
  "F2L30": "R U R' U' R U R'",
  "F2L31": "U' R' F R F' R U' R'",
  "F2L32": "U R U' R' U R U' R' U R U' R'",
  "F2L33": "U' R U' R' U2 R U' R'",
  "F2L34": "U R U R' U2 R U R'",
  "F2L35": "U' R U R' U F' U' F",
  "F2L36": "U F' U' F U' R U R'",
  "F2L37": "R2 U2 F R2 F' U2 R' U R'",
  "F2L38": "R U' R' U' R U R' U2 R U' R'",
  "F2L39": "R U' R' U R U2 R' U R U' R'",
  "F2L40": "r U' r' U2 r U r' R U R'",
  "F2L41": "R U' R' r U' r' U2 r U r'",
  "COLL-A1": "y R U2 R' U' R U' R'",
  "COLL-A2": "y2 R2 D R' U R D' R' U R' U' R U' R'",
  "COLL-A3": "y2 R2 D R' U2 R D' R2 U' R U' R'",
  "COLL-A4": "y2 R' U' R U' R2 D' R U2 R' D R2",
  "COLL-A5": "y2 r' F R F' r U R'",
  "COLL-A6": "R U' R' U2 R U' R' U2 R' D' R U R' D R",
  "COLL-S1": "R U R' U R U2 R'",
  "COLL-S2": "y2 R U R' U R2 D R' U2 R D' R2",
  "COLL-S3": "L' R U R' U' L U2 R U2 R'",
  "COLL-S4": "y' R U R' U R U' R D R' U' R D' R2",
  "COLL-S5": "R U' L' U R' U' L",
  "COLL-S6": "y2 R U R' F' R U R' U R U2 R' F R U' R'",
  "COLL-L1": "y' R U R' U R U' R' U R U' R' U R U2 R'",
  "COLL-L2": "R' U2 R' D' R U2 R' D R2",
  "COLL-L3": "y R U2 R D R' U2 R D' R2",
  "COLL-L4": "y F R' F' r U R U' r'",
  "COLL-L5": "y2 F' r U R' U' r' F R",
  "COLL-L6": "y r U2 R2 F R F' R U2 r'",
  "COLL-U1": "R' U' R U' R' U2 R2 U R' U R U2 R'",
  "COLL-U2": "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R",
  "COLL-U3": "y2 R2 D R' U2 R D' R' U2 R'",
  "COLL-U4": "F R U' R' U R U R' U R U' R' F'",
  "COLL-U5": "R2 D' R U2 R' D R U2 R",
  "COLL-U6": "R2 D' R U R' D R U R U' R' U' R",
  "COLL-T1": "R U2 R' U' R U' R2 U2 R U R' U R",
  "COLL-T2": "R' U R U2 R' L' U R U' L",
  "COLL-T3": "y R' F' r U R U' r' F",
  "COLL-T4": "y2 F R U R' U' R U' R' U' R U R' F'",
  "COLL-T5": "y' r U R' U' r' F R F'",
  "COLL-T6": "R' U R2 D r' U2 r D' R2 U' R",
  "COLL-P1": "R U2 R2 U' R2 U' R2 U2 R",
  "COLL-P2": "y F U R U' R' U R U' R2 F' R U R U' R'",
  "COLL-P3": "R' U' F' R U R' U' R' F R2 U2 R' U2 R",
  "COLL-P4": "R U R' U' R' F R2 U R' U' R U R' U' F'",
  "COLL-P5": "R U' L' U R' U L U L' U L",
  "COLL-P6": "R' F' U' F U' R U S' R' U R S",
  "COLL-H1": "R U R' U R U' R' U R U2 R'",
  "COLL-H2": "F R U' R' U R U2 R' U' R U R' U' F'",
  "COLL-H3": "R U R' U R U L' U R' U' L",
  "COLL-H4": "y F R U R' U' R U R' U' R U R' U' F'",
  "2x2-oll-sune": "R U R' U R U2 R'",
  "2x2-oll-anti-sune": "R U2 R' U' R U' R'",
  "2x2-oll-pi": "F R U R' U' R U R' U' F'",
  "2x2-oll-p": "F R U R' U' F'",
  "2x2-oll-l": "y F' R U R' U' R' F R",
  "2x2-oll-t": "R U R' U' R' F R F'",
  "2x2-oll-h": "R2 U2 R' U2 R2",
  "2x2-pbl-adj": "y R U R' F' R U R' U' R' F R2 U' R'",
  "2x2-pbl-opp": "R U' R' U' F2 U' R U R' U F2",
  "2x2-pbl-opp-opp": "R2 F2 R2",
  "2x2-pbl-adj-adj": "R2 U' B2 U2 R2 U' R2",
  "2x2-pbl-adj-opp": "R U' R F2 R' U R'",
  "2x2-pbl-opp-adj": "y R2 U R2 U' R2 U R2 U' R2",
  "CLL-AS-1": "y R U2 R' U' R U' R'",
  "CLL-AS-2": "R U2 R' F R' F' R U' R U' R'",
  "CLL-AS-3": "y2 F' L F L' U2 L' U2 L",
  "CLL-AS-4": "y2 R' F R F' R U R'",
  "CLL-AS-5": "y2 R U2 R' U2 R' F R F'",
  "CLL-AS-6": "y' R U2 R' U' R U' R' F R' F' R U R U' R' U'",
  "CLL-H-1": "F R2 U' R2 U' R2 U R2 F'",
  "CLL-H-2": "R U R' U R U R' F R' F' R",
  "CLL-H-3": "y F R U R' U' R U R' U' R U R' U' F'",
  "CLL-H-4": "y R2 U2 R' U2 R2",
  "CLL-L-1": "y R U2 R' F' R U2 R' U R' F2 R",
  "CLL-L-2": "y2 R U2 R2 F2 R U R' F2 R F'",
  "CLL-L-3": "y2 R' U R' U2 R U' R' U R U' R2",
  "CLL-L-4": "y R U2 R2 F R F' R U2 R'",
  "CLL-L-5": "y F R' F' R U R U' R'",
  "CLL-L-6": "y2 F' R U R' U' R' F R",
  "CLL-Pi-1": "y F R' F' R U2 R U' R' U R U2 R'",
  "CLL-Pi-2": "R U2 R' U' R U R' U2 R' F R F'",
  "CLL-Pi-3": "y F R2 U' R2 U R2 U R2 F'",
  "CLL-Pi-4": "y2 R' F R F' R U' R' U' R U' R'",
  "CLL-Pi-5": "y' R' U' R' F R F' R U' R' U2 R",
  "CLL-Pi-6": "F R U R' U' R U R' U' F'",
  "CLL-Sune-1": "L' U2 L U2 L F' L' F",
  "CLL-Sune-2": "R U R' U' R' F R F' R U R' U R U2 R'",
  "CLL-Sune-3": "R U' R' F R' F' R",
  "CLL-Sune-4": "F R' F' R U2 R U2 R'",
  "CLL-Sune-5": "y2 R U R' U R' F R F' R U2 R'",
  "CLL-Sune-6": "R U R' U R U2 R'",
  "CLL-T-1": "y' R U R' U' R' F R F'",
  "CLL-T-2": "y L' U' L U L F' L' F",
  "CLL-T-3": "F U' R U2 R' U' F2 R U R'",
  "CLL-T-4": "R' U R U2 R2 F' R U' R' F2 R2",
  "CLL-T-5": "y2 F R U R' U' R U' R' U' R U R' F'",
  "CLL-T-6": "R' U R U2 R2 F R F' R",
  "CLL-U-1": "y' F R U R' U' F'",
  "CLL-U-2": "R' U' R2 U R' U2 R U2 R' U R'",
  "CLL-U-3": "y2 F R U R' U2 F' R U' R' F",
  "CLL-U-4": "y' F R' F' R U' R U' R' U2 R U' R'",
  "CLL-U-5": "R U' R2 F R F' R U R' U' R U R'",
  "CLL-U-6": "R' U R' F R F' R U2 R' U R",
  "EG1-AS-1": "y U2 B U' R2 F2 U' F",
  "EG1-AS-2": "U R U' R' F' U' F2 R U' R'",
  "EG1-AS-3": "F' R U R' U' R U R2 F' R",
  "EG1-AS-4": "R U' R' F' U' R U R' U' F",
  "EG1-AS-5": "y' R U R' F' U' R U R' U' R U R'",
  "EG1-AS-6": "y2 R U' R2 F R U' R' F R F'",
  "EG1-H-1": "U' R' F R2 U' R' F R U R' F'",
  "EG1-H-2": "U' F' U R U' R2 F2 R U' F",
  "EG1-H-3": "U R' F R F' U2 F R U2 R' F",
  "EG1-H-4": "U' R U R' F' R U R' U' R U R' U'",
  "EG1-L-1": "y R U' R' U R U' R2 F' R F",
  "EG1-L-2": "y' U' R' F R U' R' F R2 U R' F' U2",
  "EG1-L-3": "y R' U R2 U' R2 U' F R2 U' R'",
  "EG1-L-4": "y R' F R2 U R' F' R U2 R'",
  "EG1-L-5": "y2 R U R' F' R U R' U' F R' F' R",
  "EG1-L-6": "y2 R' U2 F R U2 R U' R2 F",
  "EG1-Pi-1": "y2 U' F U' R' F R U' F2 R U R'",
  "EG1-Pi-2": "y' R U' R2 F R2 U' R'",
  "EG1-Pi-3": "y' F R' F U' F2 R U R",
  "EG1-Pi-4": "y' R U' R' U R U' R' F R U' R'",
  "EG1-Pi-5": "R U' R2 F R U R U' R' U' R' F R F'",
  "EG1-Pi-6": "U' R' F' R U' R' F R2 U R' F' R U R'",
  "EG1-S-1": "y2 U' L F' L2 U' L F U L' U L",
  "EG1-S-2": "R U R' F2 U F R U R'",
  "EG1-S-3": "y2 F R' F' R U R' F' R2 U R'",
  "EG1-S-4": "U F' R' F R2 U R' U' F R' F' R U",
  "EG1-S-5": "y R U' R' U R U' R' U F R U' R'",
  "EG1-S-6": "R' F R2 U' R' U R U' R' F",
  "EG1-T-1": "F R U' R2 F' R U R' F' R",
  "EG1-T-2": "F' R' F R2 U R' U' R U R'",
  "EG1-T-3": "y R U' R2 F R U R U2 R'",
  "EG1-T-4": "y' U2 R' F R F' U R U' R' U F R U' R'",
  "EG1-T-5": "y' R' F' R2 U R' F' R U R'",
  "EG1-T-6": "y' U' R U' R' U2 F R U2 R' F",
  "EG1-U-1": "y U2 R U R' U R U' R2 F' R2 U R' U",
  "EG1-U-2": "U2 y R' U R' U' R U' R' U' F2 R2",
  "EG1-U-3": "F' U2 R U2 R' U2 F",
  "EG1-U-4": "y R' F R F' R' F R2 U' R'",
  "EG1-U-5": "U2 R U' R' U R U' R' U' F R U' R'",
  "EG1-U-6": "y2 R' F R U' R' F R U' R U R' F' U2",
  "EG2-AS-1": "F R2 U R' U2 R U R2 U F'",
  "EG2-AS-2": "R' U' R U' R' U2 R' F2 R2",
  "EG2-AS-3": "U2 R' F R F' R U R B2 R2",
  "EG2-AS-4": "U2 F' L F L' U2 L' U2 L' B2 L2",
  "EG2-AS-5": "y2 F R F' U R2 F' R U' R",
  "EG2-AS-6": "y2 R2 F2 R F R F' R U R'",
  "EG2-H-1": "R2 F U2 F2 R2 F' R2",
  "EG2-H-2": "y R2 B2 U2 R' U2 R2",
  "EG2-H-3": "R' U' R U2 R2 F' R U' F R",
  "EG2-H-4": "y' R U2 B2 R' U R U' B R'",
  "EG2-L-1": "U L2 B2 L U' L' U L F' L F",
  "EG2-L-2": "y2 F2 R2 F R U R' U' R' F R",
  "EG2-L-3": "y2 R2 U' R U2 R' U2 R U' F2 R2",
  "EG2-L-4": "y' R' U L' U2 R' F R U' R' U' F' x2",
  "EG2-L-5": "y F R' F' R U R U' R B2 R2",
  "EG2-L-6": "y2 F' R U R' U' R' F R' F2 R2",
  "EG2-Pi-1": "F U' R U2 R U' R' U R' F'",
  "EG2-Pi-2": "R U2 R2 U R' F2 R2 F'",
  "EG2-Pi-3": "U F R2 U' R2 U R2 U R2 F R2 F2 U2",
  "EG2-Pi-4": "y2 R' F R F' R U' R' U' R U' R F2 R2",
  "EG2-Pi-5": "U' R' F' R' F2 R2 U R' U2 R U",
  "EG2-Pi-6": "U R' U2 R U' R2 F2 R F R U'",
  "EG2-S-1": "R2 F2 R U R U' R' F R' F' R2 U R' U' R",
  "EG2-S-2": "R U R' U R U2 R B2 R2",
  "EG2-S-3": "R U' R' F R' F' R' F2 R2",
  "EG2-S-4": "F R' F' R U2 R U2 R B2 R2",
  "EG2-S-5": "R' U R' F R2 U' F R' F'",
  "EG2-S-6": "R2 B2 R' U' R' F R' F' R",
  "EG2-T-1": "U R' F' R U R U' R' F' R2 B2 U",
  "EG2-T-2": "y' F U' R2 U' R' U R2 F'",
  "EG2-T-3": "R' U R U2 R2 F' R U' R",
  "EG2-T-4": "R2 F2 R U' F R' F' R U R",
  "EG2-T-5": "y' R' U2 R U' R' F R' F R F' R",
  "EG2-T-6": "y R' U2 R' F2 R F2 R",
  "EG2-U-1": "R2 U2 R U R' U F' R U' R",
  "EG2-U-2": "y' F R U R' U' F R2 B2",
  "EG2-U-3": "R' F' U' R U2 R' U F R",
  "EG2-U-4": "R' F' U' F U2 L' U2 R U' L",
  "EG2-U-5": "y2 R2 B2 R' U R' U' R' F R F'",
  "EG2-U-6": "y2 R2 F2 R F' R U L F' L' F"
};

export const ALG_VALID_ALTS: Record<string, string[]> = {
  "OLL1": [
    "L' U2 L2 F' L' F U2 L F' L' F",
    "R' U' F R' F' R2 U R f' U' f",
    "r' U' R U' R' U2 r U r U2 R' U' R U' r'",
    "M R U R' U R U' R' U r U2 r' U' M'",
    "r U R' U R' r2 U' R' U R' r2 U2 r'",
    "R U B' R B R2 U' R' F R F'",
    "U' R U' R2 D' r U' r' D R2 U R'",
    "R U R' S R' U' R U R S' U F R' F' R",
    "F R U R' U' F' U2 F U R U' R' F' r U R' U' r' F R F'",
    "r U2 R2 U' R U' r' U2 F R F'",
    "R U R' U R U' R' U R U2 R' S R' U' R U R U R U' R' S'",
    "y F U R U' R' F' R U R' U R U' y R U' R' F'",
    "r U R' U R' r2 U' R' U R' r2 U2 r' U'",
    "R U2 R' l' U l F' U2 R' F R F'",
    "y F U R' F R F2 U' y' R' F R F'",
    "R U B' l U l2 x' U' R' F R F'"
  ],
  "OLL2": [
    "F R U R' U' F' f R U R' U' f'",
    "R' U2 r U' r' U2 r U r' U2 R",
    "r' D R2 U R' U2 R U' R2 D' r",
    "F R' F' U2 r U R' U R2 U2 r'",
    "U r U r' U2 r U2 R' U2 R U' r'",
    "F R U R' U' F' U2 F U R U' R' F'",
    "U L F L' U2 R U2 R' U2 r U' r'",
    "R U2 R2 F R F' U2 R' F R F' U2 F R' F' r U R U' r'",
    "U' R U' R2 D' r U r' D R2 U R'",
    "r' U' r R' U' R U' R' U R U2 r' U r",
    "U' R2 F R F' U' R U' R2 F R F' U R",
    "U' F R' F' R U' F' U' r U2 R' U r' F2 R",
    "U' R U R' S U' R' U S' U R' U F' U F R",
    "U2 F R' F' R U2 F R' F' R2 U2 R'",
    "U F R' F' R U2 R U' R' F' r' F2 r U F",
    "U R U R' U' R f R f' U R' F' U' r U' r' F2",
    "F R' F' R U R U' f R f' U R' U' R U' R'",
    "R U R' U2 F' U' L' U L U F U' R U2 R'",
    "U' F' L' U L F' L' U L F U' R' F R2 U' R'"
  ],
  "OLL3": [
    "M R U R' U r U2 r' U M'",
    "F U2 F R' F' R U R U R' U F'",
    "M U l' U2 l U L' U L M'",
    "R r' U R' F2 R U r' F r2 R'",
    "R f' U' f U R D r' U' r D' R'",
    "L F' L' F U S' L U L' U' L' S",
    "R U R' S U R U' R' S2 R U' R' S",
    "U F R U' R' U' R U R' U' R' F R F' R U R' F'",
    "U' F R U R' U' F' R U R' F' U2 F R U' R'",
    "F R' F' R U' S U' R U R' S' R U R'",
    "U' f R U R' U' f' U' F R U R' U' F'",
    "r' R2 U R' U r U2 r' U r R'",
    "L' l U R' F2 R U L' U L r R'",
    "r' R2 U R' U r U2 r' U R' r",
    "r U R' U R U2 r' U r U R' U' r' R U R U' R'"
  ],
  "OLL4": [
    "R' F R F' U' S R' U' R U R S'",
    "R' F' U' F U R f R U R' U' f'",
    "U' f R U R' U' f' U F R U R' U' F'",
    "r' R U' r U2 r' U' R U' R2 r",
    "M r' F' r U' R' F2 R U' M'",
    "y' f R U R' d' l' F R U R' U' F'",
    "F' U2 F' L F L' U' L' U' L U' F",
    "l' U' L U' L' U2 l U r' U' R U R' r U' R' U R",
    "M U' r U2 r' U' R U' M' R'",
    "U' R' F2 R2 U2 R' F' R U2 R2 F2 R",
    "L' U' L U' L' U2 L R U R' U' M' U R U' r' U2 r U R' U' M U R U' R'",
    "M L' U' L U' l' U2 l U' M'",
    "U' R' U' F' U' F R U' R' F' U' F U' R"
  ],
  "OLL5": [
    "F R U R' U' F' U' F R U R' U' F'",
    "U2 l' U2 L U L' U l"
  ],
  "OLL6": [
    "F U' R2 D R' U' R D' R2 U F'",
    "L F2 l' U' l F' L'",
    "R U' R' U2 r U' r' U' r U r'",
    "L F2 R' F' R F' L'",
    "F R U R' U' F' U' F U R U' R' F'",
    "F R U R' U' F' U f R U R' U' f'",
    "F' U' F2 R' F' R U R U2 R'",
    "U2 l U2 L' U' L U' l'"
  ],
  "OLL7": [
    "S' R U R' U R U2 R' U S",
    "L' U2 L U2 L F' L' F",
    "F R' F' R U2 R U2 R'",
    "r U r' U R U' R' r U' r'",
    "L F R' F R F2 L'",
    "r' F2 r U2 L F' L' F"
  ],
  "OLL8": [
    "l' U' L U' L' U2 l",
    "R U2 R' U2 R' F R F'",
    "R' F' r U' r' F2 R",
    "S L' U' L U' L' U2 L U' S'",
    "R' F' r U' L' U2 l",
    "l' U' l U' L' U L l' U l",
    "R' F R U' R' F' R U2 L' U' L",
    "U2 L' B' R B' R' B2 L",
    "R' F' R U' L' U L R' F R",
    "U2 r' U' R U' R' U2 r",
    "R' F' L F' L' F2 R",
    "F' L F L' U2 L' U2 L"
  ],
  "OLL9": [
    "R U2 R' U' S' R U' R' S",
    "M R U2 R' U' R U' R' U' M'",
    "y R' U' R y' x' R U' R' F R U R' x",
    "U R' U' R U' l U' R' U x R' U2 R",
    "y R' U' R y' l U' l' U R B R'",
    "U R' U' R F R' F' U F R F'",
    "y' L' U' L y l U' l' U l U l'",
    "r' R2 U2 R' U' R U' R' U' R' r",
    "U R U R' U' R' F R2 U R' U' F'",
    "y R' U' R y' R B' R' U R B R'"
  ],
  "OLL10": [
    "R U R' U l' U R U' l U2 R'",
    "U R U R2 F' U' F R2 U' R2 U2 R",
    "R' U' R2 f R f' U' R' U R' U R",
    "U r R2 U2 R U R' U R U R r'",
    "U2 L U L' F' L F U' F' L' F",
    "R U R' U x R' U R U' R x' U2 R'"
  ],
  "OLL11": [
    "S R U R' U R U2 R' U2 S'",
    "M R U R' U R U2 R' U M'",
    "r' R2 U R' U R U2 R' U R' r",
    "U2 R U R' U' R' F R F' L' U' L U L F' L' F",
    "R U R' U R U' R' S' R U' R' S",
    "R U R' U R U R' S' R U R' S",
    "U2 r U R' U R' F R F' R U2 r'"
  ],
  "OLL12": [
    "F R U R' U' F' U F R U R' U' F'",
    "S U' R' U' R U' R' U2 R S'",
    "U' l' U' L U' L F' L' F L' U2 l",
    "S F' U' F U' F' U2 F U' S'",
    "U' M' R' U' R U' R' U2 R U' M",
    "y3 R2 r U' R U' R' U2 R U' R r'",
    "U' r R2 U' R U' R' U2 R U' R r'",
    "U l L2 U' L U' L' U2 L U' L l'",
    "R U R' U' R' F R F' U R U R' U' R' F R F'"
  ],
  "OLL13": [
    "F U R U' R2 F' R U R U' R'",
    "r U' r' U' r U r' F' U F",
    "L F' L' U' L F L' F' U F",
    "F U R U2 R' F R' F' R U F'",
    "l' U' L U l F' L2 U' L U F",
    "L' U' L U R U R' U' L F' L' F R U R' U R U' R'",
    "R U R' U' R' F R F' R U R' U R U2 R'",
    "R U R' U' M' U R U' M U R' U R U2 R'",
    "R U' L' U R' U' L R U R' S' R U' R' S"
  ],
  "OLL14": [
    "r U R' U' r' F R2 U R' U' F'",
    "l' U l U l' U' l F U' F'",
    "F' U' L' U L2 F L' U' L' U L",
    "F' U' L' U2 L U L' U' L F",
    "F' U' r' F2 r U' F R U' R'",
    "F' U' r' F r2 U r' U' r' F r",
    "R' F R U l' U' l F U' F'",
    "R U R' U r' U' R2 U' R2 U2 r",
    "F U R U' R2 F' R U2 R U' R' U R U2 R'",
    "F' U' L' U2 L F U' R' F R F'",
    "r' F' r U' r' F2 r2 U R' U' r' R U R U' R'",
    "L' U2 R U R' U2 L U R' F R F'",
    "L' U' L U L F' L' F L' U' L U' L' U2 L",
    "F R U' R' U R2 D R' U R D' R2 F'",
    "F R2 U D R2 D' R' D R' U' D' R2 F'"
  ],
  "OLL15": [
    "f U f' R' f R U' R' f' R",
    "F U R U' R D R' U' R D' R2 U' R U R' F'",
    "L F' L' U' L U F L' U L U2 L'",
    "y2 U2 y2 U2 r' U' r R' U' R U r' U r",
    "U2 F R U R' U' F' U R U R' U R U2 R'",
    "U2 R U2 R' U' R U R' U' R U R' U2 R' F R F'",
    "U2 L F' L' F L' U L U' L' U' L U' F U F'",
    "U2 l' U' R r' U' L U R' F R",
    "U2 l' U' l L' U' L U l' U l",
    "L' B' L R' U' R U L' B L",
    "L' B' L R' U' R U r' U r"
  ],
  "OLL16": [
    "R U' R' S R U' R' U S' U2 R U' R'",
    "L F L' R U R' U' L F' L'",
    "R' F R F' R U' R' U R U R' U F' U' F",
    "R U R' U' R' F R2 U R' U' R' F' R U R U' R'",
    "f R U R' U' R U R' U' f' U' R U R' U R U2 R'",
    "R U R' S R U R' U' S' R U' R'",
    "L F L' R U R' U' r U' r'"
  ],
  "OLL17": [
    "f R U R' U' f' U' R U R' U' R' F R F'",
    "l U' l' f R2 B R' U R' U' f'",
    "F' r U r' U2 r' F U' F U r",
    "U2 F R' F' R U S' R U' R' S",
    "R B' R' f R2 B R' U R' U' f'",
    "U F U R U' R' U' R' F R F' R U R' F'",
    "y x' R U' R' U y' R S U R' U' S' z'",
    "r U' r U' r2 U r2 U r' R' U2 R U r'",
    "F' U' L' U L U L F' L' F L' U' L F",
    "U2 r U' r' F U2 F U' R U' R' F'"
  ],
  "OLL18": [
    "r U R' U R U2 r2 U' R U' R' U2 r",
    "R D r' U' r D' R' U' R2 F R F' R",
    "F R' F' R U R U' R' U F R U R' U' F'",
    "F R' F' R U2 F R' F' R U' R U' R'",
    "l' U' L U' L' U2 l2 U L' U L U2 l'",
    "f U R U' R' f' U l' U' L U' L' U2 l",
    "U2 R U R' U' L' U' L U R' F R F' L' U' L2 F' L' F",
    "f R U R' U' f' U' r U' r' U' r U r' F' U F",
    "r U R' U R U2 r' U2 R U2 R' U2 R' F R F'",
    "r U R' U R U2 r' U2 l' U' L U' L' U2 l"
  ],
  "OLL19": [
    "M U R U R' U' M' R' F R F'",
    "R' U2 F R U R' U' F2 U2 F R",
    "r' R U R U R' U' r R2 F R F'",
    "r' U2 R U R' U r2 U2 R' U' R U' r'",
    "M U' L' U' L U M' L F' L' F",
    "F' L F L2 U L F R' F' R U' L' U L U R U' R'",
    "r' R U R U R' U' R2 r F R F'",
    "U2 F R' F' R U R U' R' U' F R U R' U' F'"
  ],
  "OLL20": [
    "M' U2 M U2 M' U M U2 M' U2 M",
    "S R' U' R U R U R U' R' S'",
    "R U R' U' R' F R F' R U2 R2 F R F' R U2 R'",
    "M' U' M' U' M' U' M' U M' U' M' U' M' U' M' U'",
    "M' U2 M U2 M' U' M U2 M' U2 M",
    "r' R U R U R' U' R2 r2 U R U' r'",
    "M U M U M U M2 U M U M U M U M U M U M U M2 U M U M U M U",
    "S U' R U R' S2 R U' R' S",
    "R2 S' R2 U' S2 U' R2 S' R2",
    "S' R U R' S2 R U' R' U S'",
    "M U M' U2 M U M' U M U M' U2 M U M'",
    "f R U R' U' f' R' F' U' F R U' R' U2 R",
    "F U R U' R' F' U2 R' U' R' F R F' U R",
    "M U M F R' F' M2 F R F'",
    "f R U R' U' f' R' U' R' F R F' U R",
    "r' R U R U R' U' L2 l2 U R U' r'",
    "M' U M' U M' U M' U' M' U M' U M' U M'",
    "R U R' U' M' U R U' r' U2 r U R' U' M U R U' R'",
    "F R' F R2 U R' U' F2 U' L F' L' F",
    "F R' F' R M2 R' F R F' M' U' M'",
    "M' U2 M U2 M' U' M U2 M' U2 M U",
    "M' U M U2 M' U M U M' U M U2 M' U M",
    "R U' R2 F2 U' R F' R' U F2 R2 U R'",
    "y F' L F M2 F' L' F M' U M'",
    "S R U R' U' R' U' R' U R S'",
    "r U R' U' r' R U S' R U' R' S",
    "U M' U M' U M' U M' U' M' U M' U M' U M'",
    "M' U' M U2 M' U' M U' M' U' M U2 M' U' M",
    "R' F R S2 R' F' R S' U S'",
    "r U R' U' r2 R2 U R U' R' U' R' r",
    "M U M U M U M U M' U M' U M' U M' U",
    "r U R' U' r2 R2 U R U' R' U' r R'",
    "M' U2 M' U2 M' U M U2 M U2 M U",
    "R U' R2 F2 U' R F R' U F2 R2 U R'",
    "M' U' M' U' M' U' M' U' M U' M U' M U' M U'",
    "L R' F2 L' R U2 L R' F L' R U2 L R' F2 L' R",
    "M' U' M' U' M' U' M' U M' U' M' U' M' U' M'",
    "r' R U R U R' U' r2 R2 U R U' r'",
    "M U2 M' U2 M U M' U2 M U2 M'"
  ],
  "OLL21": [
    "R' U' R U' R' U R U' R' U2 R",
    "y F R U R' U' R U R' U' R U R' U' F' y'",
    "L U L' U L U' L' U L U2 L'",
    "R U R' U R U r' F R' F' r",
    "U y2 R2 U' L2 F2 L' F2 L D' F2 D' L D2 L' F2 L' F2 L D' F2 D' L D2 L U R2 y2 U'",
    "y R U2 D2 R' U' R U' R' U2 R D2 R' U y R U2 D2 R' U' R U' R' U2 R D2 R' U",
    "U' F R U R' U' R U R' U' R U R' U' F'",
    "U F R U R' U' R U R' U' R U R' U' F'",
    "F R U' R' U R U2 R' U' R U R' U' F'",
    "R2 U' L2 F2 L' F2 L D' F2 D' L D2 L U R2",
    "U F R U R' U' R U R' U' R U R' U' F' U'",
    "L' U' L U' L' U L U' L' U2 L",
    "R U R' U R U2 U R' U R U2 R'",
    "L' U R U' L U R' U' R U2 R' U' R U' R'",
    "R B U B' U' B U B' U' B U B' U' R'",
    "U R U2 R' U' R U R' U' R U' R'",
    "U R U2 R' U' R U R' U2 R' F R2 U' R' U' R U R' F' U2",
    "U' f R U R' U' R U R' U' R U R' U' f'",
    "R U R' U R U L' U R' U' L",
    "R' F' R U2 R U2 R' F U' R U' R'"
  ],
  "OLL22": [
    "R' U2 R2 U R2 U R2 U2 R'",
    "f R U R' U' f' F R U R' U' F'",
    "R U R' U' R' U2 R U R' U R2 U2 R'",
    "R U' L' U R' U' L U' R U R' U R U2 R'",
    "R' U' R U' R' U2 R U R' U' R U' R' U2 R",
    "F S R U R' U' S' R U R' U' F'",
    "R U' z U' R D' R U R U' R U z'",
    "U' r U R' U R' F R F' R U' R' U R U2 r'",
    "R U' L' U R' U L U L' U L",
    "R U D' R U R' D R2 U' R' U' R2 U2 R",
    "R U2 R' U' R U' R' U' R U2 R' U' R U' R'",
    "R' F' U' F U' R U S' R' U R S",
    "R U R' U' R' F R2 U R' U' R U R' U' F'",
    "R2 D' R U R' D R U R U' R' U R U R' U R",
    "R U R' U R U2 R' U' R U R' U R U2 R'",
    "U' F U R U2 R' U R U R' F' R U2 R' U' R U' R'",
    "R' U' F' R U R' U' R' F R2 U2 R' U2 R",
    "R' U2 R U R' U R U R' U2 R U R' U R U"
  ],
  "OLL23": [
    "R U R' U R U2 R2 U' R U' R' U2 R",
    "R U' L U' R' U L' U2 R U' R'",
    "R2 D R' U2 R D' R' U2 D D' R'",
    "L2 D' L U2 L' D L U2 L",
    "U F R U R' U' F' r U R' U' r' R U R U' R'",
    "U2 R2 D' R U2 R' D R U2 R",
    "U2 R2 D' R U R' D R U R U' R' U' R",
    "R U R' U R U2 R' U R U2 R' U' R U' R'",
    "U r U R' U' r' F R F' R' F' L' F R F' L F",
    "R' D R D' R' D R U' R' D' R D R' D' R U",
    "R U2 R' U L' U2 R U' R' U2 L",
    "x2 D' R U R' U' R U R' U' D' U R U' R' U R U' R' x2",
    "y' U R' U2 L F2 L' F2 R2 U2 R U2 R' U2 F2 R2 F2 U' y",
    "R U R' U R U2 R' U R U2 R' U' R U' R' U",
    "R' D R D' R' D R U' R' D' R D R' D' R",
    "U R' U' R U2 R D R' U2 R D' R2 U R",
    "U R U R' U2 R' D' R U2 R' D R2 U' R'",
    "U2 R' U' R U' R' U2 R2 U R' U R U2 R'",
    "R' F2 R U2 R U2 R' F2 R U2 R'",
    "x' R U R' U' R U R' D R U' R' U R U' R' D' x",
    "R U' L' U R' U' L U2 L' U R U' L U R'",
    "R U2 x R U2 R U2 R' U2 L U2 r' U2 R U2 R' U2 R'",
    "R U2 x R U2 R U2 r' U2 L U2 R' U2 R U2 R' U2 R'",
    "U2 R' F R U' R' U' R U R' F' R U R' U' R' F R F' R",
    "R' U2 L F2 L' F2 R2 U2 R U2 R' U2 F2 R2 F2",
    "U' R U2 R' U' R U' R' U' R U R' U R U2 R'",
    "x2 R2 U R' D2 R U' R' D2 R' x2",
    "R U R' U R U2 R' U2 L' U' L U' L' U2 L",
    "U' R' U' R U' R' U2 R U' R' U2 R' D' R U2 R' D R2 U",
    "R2 D R' U2 R D' R' U R U R U R U' R' U' R2 U2",
    "U' R U2 R' U' R U' R' U2 R' U2 R U R' U R",
    "U' R' U R' D' U' R U' R' U2 R U' R' D R U' R U'",
    "R2 B2 U2 L U2 R' U2 R U2 F2 R F2 L' B2 R2",
    "L' U' L U' L' U2 L2 U L' U L U2 L'"
  ],
  "OLL24": [
    "L F R' F' L' F R F'",
    "x U R U' L U R' U' L' x'",
    "U' x' R U R' D R U' R' D' x",
    "F R F' r U R' U' r'",
    "U R' F' R U R' U' R' F R U R",
    "U' F R' D' R U R' D R U' F'",
    "U2 x R' U' L U R U' L' U x'",
    "r' U' R U L U' R' U x",
    "R U R' U R U2 R' L' U' L U' L' U2 L",
    "U2 R' F' r U R U' r' F",
    "U R' U2 R U R2 F R U R U' R' F' R",
    "U R U R D R' U' R D' R2",
    "U2 R' F' L F R F' L' F",
    "U' R' U' R' D' R U R' D R2",
    "x L U R' U' L' U R U' x'",
    "r U R' U' r' F R F' U",
    "U F R U' R' U' R U2 R' U' F' R' U' R U' R' U2 R U",
    "U R' U D' R U2 R' D R' U' R U2 R' U' R2",
    "U2 R U' R2 D' r U2 r' D R2 U' R' U' R U' R'",
    "R' U' R U' R' U2 R U2 R U R' U R U2 R'",
    "r U R' U' L' U l F'",
    "x' L D R' D' L' D R D' x",
    "R U R' U' L' U R U' R' L",
    "R' U' R F R' U R U' F'",
    "r' U' R U r f' U' f"
  ],
  "OLL25": [
    "F R' F' r U R U' r'",
    "x R' U R D' R' U' R D x'",
    "R' F R B' R' F' R B",
    "L' R U R' U' L U R U' R'",
    "L U L' U L U' L' U L U' L' U L U2 L'",
    "L' U' L U' B U' L' U' L U B'",
    "r U2 R2 F R F' R U2 r'",
    "x U R' U' L U R U' L' x'",
    "U' R U R' U' R' F R U R U' R' F'",
    "U F' r U R' U' r' F R",
    "F l' U' L U R U' r'",
    "U R U2 R2 D' R U' R' D R2 U' R'",
    "x U R' U' r x' U R U' r'",
    "L' U' L R U2 L' U' L U2 R'",
    "U' r U R U' L' U R' U' x'",
    "x U R' U' L U R U' r'",
    "L' B' R' B L B' R B",
    "x' L' U' R' U L U' R U x",
    "R U R D R' U R D' R' U2 R'",
    "R L' U R' U' L U R U' R'",
    "R U R' U R U2 R' U2 R U2 R' U' R U' R'",
    "U B' R' F' R B R' F R",
    "U2 R' U' F U F' R F U' F'",
    "l' U R D' R' U' R D x'",
    "U R2 D R' U R D' R' U' R'",
    "R U2 R' U' R U' R' U2 R U R' U R U2 R'",
    "U2 R2 D' R U' R' D R U R",
    "U' x' R U' R' D R U R' D' x",
    "U F R U R' U' R' F' U' R U R U' R' U' R' U R",
    "R U R D R' U2 R D' R' U' R' U R U R' U",
    "R2 U' R U R U' R D' U R U' R' D U'",
    "U' R' U2 R' D' R U2 R' D R2",
    "R2 D' R U2 R' D R U2 R2 U2 R' U' R U' R' U",
    "R U2 R D r' U2 r D' R2 U2",
    "U2 R' F' L' F R F' L F",
    "F R' F' L F R F' L'",
    "R' F R U R' U' R' F' R U R"
  ],
  "OLL26": [
    "R' U' R U' R' U2 R",
    "U R U2 R' U' R U' R'",
    "R' U L U' R U L'",
    "B U2 B' U' B U' B'",
    "U2 L' U R U' L U R'",
    "U2 L' U' L U' L' U2 L",
    "y2 L' U' L U' L' U2 L y2"
  ],
  "OLL27": [
    "R U' L' U R' U' L",
    "y' R' U2 R U R' U R y",
    "U L' U2 L U L' U L",
    "R U' r' F R' F' r",
    "U' R' U2 R U R' U R"
  ],
  "OLL28": [
    "R' F R S R' F' R S'",
    "r U R' U' r' R U R U' R'",
    "M U M' U2 M U M'",
    "S' R U R' S R U' R'",
    "r U R' U' r' F R2 U' R' U' R U R' F'",
    "U' M' U' M U2 M' U' M",
    "M' U' M U' M' U' M U' M' U' M",
    "U r' U r2 U' r2 U' r2 U r2 U r2 U' r2 U' r2 U r'",
    "L R F R2 F R' L D' R2 D2 F2 L2 B2 U' R2 B2",
    "F R' F' R L' U R U' R' L",
    "R L' B L R' U2 R L' B L R'",
    "M' U' M U' M' U' M U' M' U' M U'",
    "r U R' U' r' U2 R U R U' R2 U2 R",
    "M2 U' M U2 M' U' M' U' M' U2 M U' M'",
    "F R U R' U' F2 L' U' L U F",
    "U' R U R' F' R U R' F' R U R' U' R' F R2 U' R' U' F R U' R'",
    "F R U R' U' F' U2 F R U R' U' F'",
    "U r U R' F' R U R' U' R' F R2 U' r'",
    "R F D2 r2 D2 F r2 D2 R"
  ],
  "OLL29": [
    "M U R U R' U' R' F R F' M'",
    "R' U' R U' R' U2 F R U R' U' F' U R",
    "L2 U' L B L' U L2 U' L' B' L",
    "U R U R' U' R U' R' F' U' F R U R'",
    "f' L' U' L2 U L U' L2 U L f",
    "L2 U' L B L' U L2 U' r' U' r",
    "x' U' R U' R2 F x R U R' U' R B2"
  ],
  "OLL30": [
    "f R U R2 U' R' U R2 U' R' f'",
    "l2 D l' U' l D' l2 U l U l'",
    "R2 U R' B' R U' R2 U R B R'",
    "U' F R U' R' U R U R' U R U' R' U R U' R' F'",
    "U' r' D' r U' r' D r2 U' r' U r U r'",
    "R U R' U R U' R' U R U' B U' B' R'",
    "M U' L' U' L U L F' L' F M'",
    "U2 F U R U2 R' U' R U2 R' U' F'",
    "R2 U R' B' R U' R2 U l U l'"
  ],
  "OLL31": [
    "y2 F f' L' U' L U L F' L' f y2",
    "R' d' L d R U' R' F' R",
    "F' U' L' U L F l' U' L U l F' L' F",
    "R' U f R U R' U' f' U2 R",
    "r U2 R' U' R2 U' L' U R' U' x'",
    "M' U R U' M U2 R' U' F' U' F",
    "z D' R' F z' U R U' R' F' R",
    "R' U' F U R U' R' F' R U"
  ],
  "OLL32": [
    "R U B' U' R' U R B R'",
    "R U2 R' U' F' U F R U' R'",
    "U2 L U F' U' L' U L F L'",
    "l F U' F' l' U l U l'",
    "F' f R U R' U' R' F R f'",
    "R d L' d' R' U l U l'",
    "U2 L U F' U' L' U r U r'",
    "S R U R' U' R' F R F' S'",
    "U' R' U2 R U R' U2 F' U' F R U R' U2 R",
    "y2 z u' R2 U R U2 R D R' U R z x'",
    "l F U' F' R' F R U l'",
    "R U B' U' R' U l U l'",
    "U2 L d R' d' L' U L F L'",
    "f F' R U R' U' R' F R f'",
    "U' F R' F' r U R U R' U' R U' r'",
    "r' U2 R U R2 U L U' R U x"
  ],
  "OLL33": [
    "R U R' U' l' U R U' x'",
    "U2 L' U' L U L F' L' F",
    "R U R' F' U' F R U' R'",
    "R' U' R U R f' U' f",
    "F R U' R' U R U R' F'",
    "R U R' U' R U' B' R B R2",
    "R' U' R U R' U F R' F' R2"
  ],
  "OLL34": [
    "F R U R' U' R' F' r U R U' r'",
    "R U2 R' F R U R' U' F' U R U R'",
    "R U2 R' U R' F' U' F U R2 U R'",
    "U2 R U R' U' B' R' F R F' B",
    "r U2 R' U' R U2 r' F U L' U2 L F U' F'",
    "R' U' R M U f R f' U2 M'",
    "x U2 R2 U r' U' r B U' R2 U2 x'",
    "R U R' U' R' F R F' R' U' R U' R' U2 R",
    "R U R' F' R U R' U' R' F R U R U' R' U' R' F R F'",
    "L U L2 U' L' B L U L U' B'",
    "U2 R U R2 U' R' F R U R U' F'",
    "F' L' U' L U L F l' U' L' U l",
    "F R U R' U' F' U F' r U R' U' r' F R",
    "R' U' R U F R B' R' F' B",
    "F R F' r U R' r' R U R' U' r U' r'"
  ],
  "OLL35": [
    "f R U R' U' f' R U R' U R U2 R'",
    "R' U2 R U R' U R U2 F R U R' U' F'",
    "F' U2 F U r U' r' U r U r'",
    "y' R' U2 R y U r U' r' U r U r'",
    "y' R' U2 R U y r U' r' U r U r'",
    "U' x' R' F2 R2 U' R' U R' F2 R x",
    "R U2 R2 x U R U' R x' U2 R'",
    "F' U2 F2 R' F' R F' U2 F"
  ],
  "OLL36": [
    "R U R' U' F' U2 F U R U R'",
    "R' U' R U' R' U R U l U' R' U x",
    "R' U' R U' R' U R U R f' U' f",
    "R U2 r D r' U2 r D' r' R'",
    "R U R' U2 F' U' F U' R U' R'",
    "R' U' R U' R' U R U R B' R' B",
    "U R U R2 F' U' F U R2 U2 R'",
    "R U R' U R' F R F' U' R U R' U' R U' R'",
    "R' U' R U' R' U2 R2 U R' U' R' F R F'",
    "L' U2 L r U2 R' U' R U2 r' F",
    "R U B U' B' U2 R' U' R U' R'",
    "L U L' B' L U L' U' L' B L U' L' B L B'",
    "L' U' L U' L' U2 L U F R U R' U' F'",
    "F R U R' U' F' U' r' U2 R U R' U r",
    "U2 L' U' L U' L' U L U L F' L' F",
    "R' F' U2 F R U2 R' U' R U2 R' U2 R",
    "F U2 r U2 r' F U2 F2 U2 F r U r'",
    "R U2 R2 F2 r U' R U2 r' F",
    "R' U' R U' R' U R U R x' U' R' U x",
    "R U R' d' L' U2 L d R U R'",
    "U2 l' U' L U' L' U2 l R U R' L' U2 R U' R' U2 L U R U' R' U",
    "U2 R' F' r U' r' F2 U' R U R' U' R2 D R' U R D' R' U2 R' U R",
    "U2 R U R' F' R U R' U' R' F R U' R' F R F'"
  ],
  "OLL37": [
    "F R U' R' U' R U R' F'",
    "R' F R F' U' F' U F",
    "y r U' r' F d R U' R'",
    "R U R' U' R' F R F' R U R' U' R' F R F'",
    "R' F' U F U F' U' F R",
    "R' U' R B U' B' R' U R",
    "y L F' L' F y' U R U' R'",
    "y M' U' M R' F R U y' R U' R'",
    "F l' U' l U l F' l'",
    "U' R U2 R' F R' F' R2 U2 R'",
    "U F' r U r' U' r' F r"
  ],
  "OLL38": [
    "r U R' U' r' F R U R U' R' F'",
    "l' U l2 D' l2 U l2 U' l2 U' D l",
    "r U R' U R U' R' U' r' F R F'",
    "U2 F R U' R2 F R F' U' F2 r U r2 F2 r",
    "L' U' L F L' U' L U L F' L' U L F' L' F",
    "R' U2 r' D' r U2 r' D R r",
    "U L' U' L2 F U F' U' L2 U2 L",
    "R U R' U R U' R' U' R' x U R U' x'",
    "y2 L U L' U L U' L' U' y2 R' F R F'"
  ],
  "OLL39": [
    "F R' F' U' F U R U' F'",
    "r U R' U R' F R F' U2 r' F R F'",
    "R' r' D' r U' r' D r U R",
    "U' F R U R' U' R U R' U' R U' R' U' R U R' F'",
    "F U F' L' U' L U F U2 F'",
    "U F R U R' U' F' R' U' R U' R' U2 R",
    "U' R U R' F' U' F U R U2 R'"
  ],
  "OLL40": [
    "R r D r' U r D' r' U' R'",
    "M F' L F L' U' L' U L U M'",
    "U F R U R' F' R' F U' F' U R",
    "r' R F' r U r' U' r' F r U r R'",
    "B' R B U B' U' R' U B",
    "U R' F R U R' U' F' U R",
    "U' R U R' U' R' F R F' r U R' U' r' F R F'",
    "M F' r U r' U' r' F r U M'"
  ],
  "OLL41": [
    "M U' F' L' U' L U F M'",
    "F R U' R' U2 S' R U R' F' S",
    "R U' R' U2 R U f R' f' U' R'",
    "R U' R' U2 R U B U' B' U' R'",
    "f R U R' U' f' U' R U R' U R U2 R'",
    "U' r U R' U R U' R' U R U' R' U' L' U l F'",
    "r' M U' F' U F r U' M'",
    "L U L' U L U2 L' B L U L' U' B'",
    "y' L F' L' F L F' L' F L' U' L U L' U' L y",
    "U2 R U R' U R U2 R' F R U R' U' F'",
    "L U L' U L U2 L' F' L' U' L U F"
  ],
  "OLL42": [
    "y R' U' F2 u' R U R' D R2 B",
    "M U F R U R' U' F' M'",
    "r' F r U2 r' F' U' F U F r",
    "f' L' U' L U f U L' U' L U' L' U2 L",
    "R B U B' R' S' R U' R' S",
    "B' U' R2 D' R U R' D R2 B",
    "U F R' F' R U2 R' U' R2 U' R2 U2 R",
    "M R B U B' U' R' U M'",
    "U l' U' L U' L' U L U' L' U L U R U' r' F",
    "R' F2 R2 U' F U' F' U2 R2 F2 R",
    "R' U' R U F R U R' U' R' U R U' F'",
    "R' U' R U' R' U2 R U R' F' U' F U R",
    "R' U' R U' R' U2 R B' R' U' R U B"
  ],
  "OLL43": [
    "f' L' U' L U f",
    "B' U' R' U R B",
    "U R' U' F' U F R",
    "r' U' R' F R F' U r",
    "x' U' F' R' F R U x",
    "y' L' d' R' U R B",
    "U2 F' U' L' U L F"
  ],
  "OLL44": [
    "B U L U3 L3 B3",
    "B L' B' L U B' U F U R' U' R F' B",
    "B L' B' L U B' U' B L F U' F' L' U'",
    "B' U R B' R' B U F U R' U' R F' B",
    "B' U R B' R' B U' B L F U' F' L' U'",
    "B' R' B L' B' R U B U B' U' B L U",
    "B' R' B L' B' R U B U' L F U' F' U'",
    "B' D B U R U B U' B' R' B' D' B U",
    "B' D B2 U L U' L' B' U B' D' B U",
    "B' D' B U R U B U' B' R' B' D B U",
    "B' D' B2 U L U' L' B' U B' D B U",
    "R U B' R B R' U' R'",
    "U2 F U R U' R' F'",
    "f R2 D R' U R D' R2 U' f'",
    "R U2 R2 F R F' U' R U' R'"
  ],
  "OLL45": [
    "f' U' L' U L f",
    "U2 F' L' U' L U F",
    "U R' F' U' F U R",
    "B' R' U' R U B",
    "F R2 D R' U R D' R2 U' F'"
  ],
  "OLL46": [
    "R' F' U' F R U' R' U2 R",
    "l' U2 L2 F' L' F U L' U l",
    "R' F' U' R U R' U' R' F R2 U' R' U R",
    "R' U' l' U R U' x' U R",
    "y F R U R' y' R' U R U2 R'",
    "M F U R U' R' F' U' M'",
    "R U R' U R U' R' F' U F R U' R'",
    "R U R B' R' B U' R'",
    "R U x' R U' R' U x U' R'",
    "R2 D r' U' r D' R2 F' U F",
    "y F R U R' F' d R U2 R'"
  ],
  "OLL47": [
    "F' L' U' L U L' U' L U F",
    "R' U' R' F R F' R' F R F' U R",
    "U' F R' F' R U2 R U' R' U R U2 R'",
    "F' r' F' r U r' F' r U F",
    "R' U' l' U R U' R' U R U' x' U R",
    "U2 f' U' r' F r U' r' F r f",
    "b' U' R' U R U' R' U R b",
    "R' F' r U' r' F2 R2 U2 R' U' R U' R'",
    "L' U2 L U L' U' L U2 L F' L' F",
    "L F' L' F U2 F U' F' U F U2 F'",
    "z F' U' R' U R U' R' U R F z'",
    "R' U' x R' U R U' R' U R U' x' U R"
  ],
  "OLL48": [
    "R U2 R' U' R U R' U2 R' F R F'",
    "F R' F' U2 R U R' U R2 U2 R'",
    "r U2 R' U' R U R' U2 r' F R F'",
    "R' U' F' U F R2 U2 R' U' R U' R'",
    "z' F U L U' L' U L U' L' b'"
  ],
  "OLL49": [
    "l U' l2 U l2 U l2 U' l",
    "R B' R2 F R2 B R2 F' R",
    "U F R' F2 R U2 R U2 R' F",
    "U2 r U' r2 U r2 U r2 U' r",
    "R f' U2 F U2 f R2 F' R",
    "R U R' U' R' F R F' U F R' F' R U R U' R'"
  ],
  "OLL50": [
    "R U R2 F R F' U F R' F' R",
    "L' U' L U r U' r' F U2 F R' F' R U R U' R'",
    "L' B L2 F' L2 B' L2 F L'",
    "U R' U2 R U R' U R f R U R' U' f'",
    "U' R U2 R' U' R U' R' F R U R' U' F'",
    "L' f U2 F' U2 f' L2 F L'",
    "R B' R B R2 U2 F R' F' R",
    "L U' y' R' U2 R' U R U' R U2 R d' L'"
  ],
  "OLL51": [
    "f R U R' U' R U R' U' f'",
    "U' R' U' R' F R F' R U' R' U2 R",
    "R U2 R' U2 R' F R2 U R' U' F'",
    "U2 F U R U' R' U R U' R' F' U2",
    "U2 F U R U' R' U R U' R' F'",
    "F' U' L' U L U' L' U L F"
  ],
  "OLL52": [
    "R U R' U R U' B U' B' R'",
    "R' U' R U' R' U F' U F R",
    "R U R' U R U' f R' f' R'",
    "R U R' U R U2 R' U F U R U' R' F'",
    "R U R' U R U' x' U F' U' R' x",
    "U F U R U2 R' U2 R U2 R' U' F'",
    "R' U' R U' R' U2 R U' f' L' U' L U f",
    "R U R' U R U2 R' U' f R U R' U' f'",
    "U r U2 R' U' R U' r' F R U R' U' F'",
    "L F U F' U L' U' L U' L'",
    "U' F R' F' r U M U R U' R' U R U' M' U' r'",
    "x' R F R' F R F' U F' U' R' x",
    "U2 R' F' U' F U' R U R' U R",
    "R' U' F' U F' L F L' F R",
    "R' U' y L' U L' y' L F L' F R",
    "r' U' R' F R F' R' F R F' U r"
  ],
  "OLL53": [
    "f R U R' U' f' L F R' F' L' F R F'",
    "f R U R' U' f' r U R' U' L' U l F'",
    "x' D' L2 U L U' L' U L U' L D x",
    "U r' U2 R U R' U' R U R' U r",
    "U2 l' U' L U' L' U L U' L' U2 l",
    "U2 F R U R' U' F' R U R' U' R' F R F'",
    "F' L F L' U2 F2 R' F' R F'",
    "y' R' F R F' U2 R2 y R' F' R F'",
    "f R U R' U' f' r U R' U' r' F R F'",
    "R U2 R' U' R U' R' U R U R' U R U' R' U' R' F R F'"
  ],
  "OLL54": [
    "F' L' U' L U F U2 R U R' U' R' F R F'",
    "F' L' U' L U F L' U' L U L F' L' F",
    "R U' R' F R' F' R F R' F' R U' R U R' U2 R U' R'",
    "U' r U2 R' U' R U R' U' R U' r'",
    "F' L' U' L U L' U L U' L' U' L F"
  ],
  "OLL55": [
    "R U2 R2 U' R U' R' U2 F R F'",
    "r U2 R2 F R F' U2 r' F R F'",
    "R' U F2 D' F U2 F' D F2 U' R",
    "R' U' F R' F' R F U R U' R' F' R",
    "R' U' F U R U' R B' R2 F' R2 B R'",
    "L' U2 L2 U L' U L U2 F' L' F",
    "L U2 L2 U' L U' L' U2 f U f'",
    "R' U2 R U R' U R U' F R U' R' U' R U R' F'",
    "R' U' R' F R F' U F' r U R U' r' F",
    "R U R' S' R U' R' S R U R' U R U' R' U R U2 R'",
    "R U R' U F R' F' R2 U' R' U' R' F' R U2 R U2 R' F",
    "R' U2 R2 U R' U R U2 f' U' f",
    "U r U2 R' U' r' R2 U R' U' r U' r'",
    "U R' F U R U' R2 F' R2 U R' U' R",
    "U R' F R U R U' R2 F' R2 U' R' U R U R'",
    "U' R' F U R U' R2 F' R2 U R' U' R",
    "R U' y R2 D R' U2 R D' R2 d R'"
  ],
  "OLL56": [
    "F R U R' U' R F' r U R' U' r'",
    "r' U' r U' R' U R U' R' U R r' U r",
    "f R U R' U' F' R U R' U' R' F R f'",
    "F R U R' U' F' r U R' U' r' F R F'",
    "R B L B' R2 f R U' R' f' R",
    "R U R' U' R' F R U R U' R' U R U' R2 F' R U R U' R'",
    "R' F' R U' L' U L U' L' U L R' F R",
    "R' F' R U' r' F r2 R' U' r' F2 R",
    "r U R U' r2 D F R' F' D' r",
    "R' F' r' D R2 D' F' r U F R'",
    "l' U' l U' L' U L U' L' U L l' U l",
    "r U R' U R U r' U' r U r' F' U F",
    "r U r' U R U' R' U R U' R' L F' L'",
    "R U R' U R U' R' S U R U' R' S' R U' R'",
    "R U R' S U R U' R' U R U' R' S' R U' R'",
    "L F L' U R U' R' U R U' R' L F' L'",
    "F R U R' U' F' L F R' F' L' F R F'",
    "U R U R' U R' U' F' U F R U R U2 R'",
    "L' B' L U' R' U R U' R' U R L' B L",
    "L' U2 R U' r B R' U2 R' U' R U' x'"
  ],
  "OLL57": [
    "R U R' U' R' r U R U' r'",
    "R U R' U' r R' U R U' r'",
    "M' U' M U M' U' M U' M' U2 M",
    "L' R U R' U' L R' F R F'",
    "M' U' M' U' M' U2 M U' M U' M U2",
    "R L' U R' U' L R' F R F'",
    "M' U M' U M' U2 M U M U M",
    "M' U M U M' U M U M' U2 M U M' U M U M' U M U",
    "M' U' M U M' U' M U' M U2 M' U' M2 U' M2 U2",
    "M' U M' U M' U M' U' M' U' M' U' M' U' M' U",
    "F R U' R' U R U R2 F' r U R U' r'",
    "M' U M U' M' U M U M' U2 M",
    "L' U' L U l' L U' L' U l",
    "M' U' M' U' M' U' M' U' M U M U M U M U",
    "M' U' M' U' M' U' M' U2 M' U' M' U' M' U' M'",
    "R U' R' F' U F R U R2 F R F'",
    "R U R' S R U' R' U S'",
    "M F R' F' M' F R F'"
  ],
  "Ua": [
    "R U R' U R' U' R2 U' R' U R' U R",
    "R2 U' R' U' R U R U R U' R",
    "M2 U M' U2 M U M2",
    "L U' L U L U L U' L' U' L2",
    "R' E' U R' E R U R' E' R E U2 R",
    "R U R' U R' U' R2 U' R' U R' U R U2",
    "B2 U' L' R B2 R' L U' B2",
    "R U R' U' L' U' L U2 R U' R' U' L' U L",
    "M2 U M' U2 M3' U M2",
    "R' U' R U' R' U2 R U R U R' U R U2 R'",
    "R U2 R U R U R U' R' U' R' U R'",
    "r U R' U R' U' R2 U' r' U R' U R U2",
    "B2 U' M U2 M' U' B2",
    "y2 R U' R U R U R U' R' U' R2 y2",
    "r U r' R U R' U' r R' U R U2 r'",
    "R2 U' R' U' R U R U R3' U' R",
    "U2 L2 U' L' U' L U L U L U' L U2",
    "r U R' U' L' U' L U2 R U' r' U' L' U L",
    "r U M U R' U' M' U R U2 r'",
    "U2 F2 U' L R' F2 L' R U' F2 U2",
    "R U R' F' L' U' L F R' U' F' U F R",
    "U2 R U' R U R U R U' R' U' R2",
    "M2 U M' U2 M U M2 U R S U U' S' R' U'",
    "U2 M2 U M U2 M' U M2 U2",
    "F' r U R' U' L' U' L U2 l F' L' U' L' U L F",
    "U2 R U' R U R U R U' R' U' R2 U2",
    "R2 U F2 L2 B2 D' B2 L2 F2 U2 R2"
  ],
  "Ub": [
    "R' U R' U' R' U' R' U R U R2",
    "M2 U' M' U2 M U' M2",
    "R' U R' U' R3 U' R' U R U R2",
    "L' U' L U' L U L2 U L U' L U' L'",
    "r U2 R' U' r' R U R U' R' r U' r'",
    "R E U2 R E' R' U' R E R' E' U' R'",
    "L2 U L U L' U' L' U' L' U L'",
    "M2 U' M' U2 M3' U' M2",
    "L' U' L U R U R' U2 L' U L U R U' R'",
    "U2 L' U L' U' L' U' L' U L U L2 U2",
    "B2 U L' R B2 R' L U B2",
    "U f' L' U' L U f F R U R' U' F'",
    "y' R U R' U' R' U R U R U' R' U' R' U' R U' R' U R U y",
    "R' U R' U' R' U' R3 U R3' U R2",
    "U M2 U M U2 M U E2 M E2 M",
    "L' U' L U r U R' U2 L' U L U R U' r'",
    "R' U' R U' R' U2 R U R U R' U R U2 R' U' M2 U M' U2 M U M2",
    "R' U R' U' R' U' R3 U R U R2",
    "R U R' U' R' U' R' U R U' S' U2 S",
    "R2 R U R' U' R' U' R' U R U R2",
    "R2 U2 F2 L2 B2 D B2 L2 F2 U' R2",
    "U2 R2 U R U R' U' R' U' R' U R'",
    "U2 R2 U R U R' U' R' U' R' U R' U2",
    "U2 M2 U' M U2 M' U' M2 U2",
    "U' M' U' M U' M' U2 M U' M' U' M U'",
    "y2 R L u2 R' U R E2 R' U' R U2 R' L'",
    "y2 R2 U R U R' U' R' U' R' U R' y2"
  ],
  "Z": [
    "M2 U M2 U M' U2 M2 U2 M'",
    "M2 U2 M U' M2 U' M2 U' M",
    "M2 u M2 u' S M2 S'",
    "M U' M2 U' M2 U' M U2 M2",
    "S M2 S' u M2 u' M2",
    "S M2 S' Uw M2 Uw' M2",
    "M2 U' M' U2 M2 U2 M' U M2",
    "M' U2 M2 U2 M' U' M2 U' M2",
    "R U R' U R' U' R' U R U' R' U' R2 U R",
    "M2 U M2 U M U2 M2 U2 M",
    "M U' M2 U' M2 U' M U2 M2 U'",
    "M2 U2 M' U' M2 U' M2 U' M' U'",
    "U R' U' R U' R U R U' R' U R U R2 U' R' U",
    "R' U' R2 U R U R' U' R U R U' R U' R'",
    "M2 D S2 D' S M2 S'",
    "M U2 M2 U2 M U' M2 U' M2 U2",
    "M2 U' M U2 M2 U2 M U M2",
    "R2 U R2 U R U2 R2 U2 R2 U2 R U' R2 U' R2",
    "R' U' R' F R F' U R U' R' U' F' U F R",
    "M2 U M2 U' E2 M E2 M",
    "M2 U M2 U M2 B2 M2 B2",
    "M' U M' U' M U M U M' U M' U' M U M",
    "M2 U M2 U' E2 M' E2 M'",
    "M2 U M2 U M' U2 M2 U2 M' U2",
    "M U' M2 U' M2 U' M' U2 M2 U2 M2",
    "y2 M2 U' M U2 M2 U2 M U M2",
    "L2 R2 D L2 R2 U L R' F2 L2 R2 B2 L R'",
    "U M' U M2 U M2 U M' U2 M2 U2",
    "R' U' R2 U R U R' U' R U R U' R U' R' U2",
    "R U R' U R' U' R' U R U' R' U' R2 U R U2",
    "U2 R U R2 U' R' U' R' U R U' R U R U' R2 U2 R U",
    "U2 M2 U M2 U M' U2 M2 U2 M' U2",
    "z D R D' R D' R' D' R D R' D' R' D2 R D z'",
    "R U R' U R' U' R' U R U' R' U' R2 U l x",
    "M' U2 M2 U2 M' U' M2 U' M2 U2",
    "R2 U' R' L' U' L U R2 U2 R2 U2 R2 U L' U L R U R2",
    "U R2 U' R2 U2 R2 U' R2 U R2 U' R2 U2 R2 U' R2",
    "M2 U M2 U M U2 M2 U2 M U2",
    "M3 U3 M2 U3 M2 U3 M3 U2 M2",
    "M U2 M2 U2 M U' M2 U' M2",
    "R2 U' R U' R U R' U R2 D' U R U' R' D R2 U' R U' R U R' U R2 D' U R U' R' D",
    "R' U R' F' R U2 R U' R' U' R' F R2 U R' U2 R",
    "R' U' F R U' R' U' R U2 R' F' R F U' F' R' U2 R",
    "U' M' U M2 U M2 U M' U2 M2",
    "S R2 U' R2 U' R2 U' R2 U' R2 U' R2 S'",
    "M2 U M2 U' M2 E2 M E2 M'",
    "M2 U2 M' U' M2 U' M2 U' M'",
    "R U R' U R3 U' R' U R U' R' U' R2 U R",
    "U M2 U' M2 U' M U2 M2 U2 M U'",
    "R L' U2 D2 R L' D' R2 L2 U F2 B2",
    "U R' U' R U' R U R U' R' U R U R2 U' R'",
    "M2 U' M2 U' M' U2 M2 U2 M U M2 U2 M2 U M2",
    "U M2 U M' U2 M2 U2 M' U' M2",
    "U2 M2 U' M' U2 M2 U2 M' U M2",
    "L U L' U L' U' L' U L U' L' U' L2 U L",
    "M2 U M2 U M2 F2 M2 F2",
    "M' U3 M2 U3 M2 U3 M' U2 M2",
    "M' U' M2 U' M2 U' M' U2 M2 U",
    "U M2 U' M2 U' M2 B2 M2 B2 U2",
    "M2 U M2 U' M' E2 M' u2",
    "M2 U M2 U' M' S2 M' S2 U2",
    "U M U M2 U M2 U M U2 M2 U'",
    "M' U' M2 U' M2 U' M' U2 M2 U'",
    "M2 U2 M' U' M2 U' M2 U' M' U",
    "R' U2 R U' R2 F' R U R U R' U2 R' F R U' R"
  ],
  "H": [
    "M2 U M2 U2 M2 U M2",
    "R2 S2 R2 U' R2 S2 R2",
    "M2 U2 M2 U M2 U2 M2",
    "M2 U2 M2 U' M2 U2 M2",
    "S R U2 R2 U2 R2 U2 R S'",
    "R2 U2 R U2 R2 U2 R2 U2 R U2 R2",
    "R2 S2 R2 U R2 S2 R2",
    "R L U2 R' L' F' B' U2 F B",
    "M2 U2 M2 U' M2 U2 M2 U",
    "M2 u' M2 u2 M2 u' M2",
    "M2 S2 M2 S2 R2 S2 R2 U' R2 S2 R2",
    "U2 S2 U2 S2 U S2 U2 S2 U",
    "F2 R2 U2 x R2 U2 R2 U2 R2 U2 x' U2 R2 F2",
    "L2 U2 L' U2 L2 U2 L2 U2 L' U2 L2",
    "M2 U' M2 U' M2 U' M2 U' M2 U' M2",
    "R2 U2 R' U2 R2 U2 R2 U2 R' U2 R2",
    "M' U2 M2 U' M2 U2 M2 U' M'",
    "M' U2 M2 U M2 U2 M2 U M'",
    "R2 U2 R E2 R2 E2 R' u2 R2 u2",
    "R2 F2 U2 R2 U2 F2 R2 F2 U2 F2 U2 F2",
    "R' U2 R U R U R2 U R2 U2 R2 U2 R",
    "R2 L2 U2 R2 L2 U R2 L2 U2 R2 L2",
    "y2 z2 y2 z2 M2 U' M2 U2 M2 U' M2",
    "R' U2 R' U' R' U' R' U R U R U' R y' R' U2 R' U' R' U' R' U R U R U' R",
    "R' U R' U' R' U' R' U R U R2 U M2 U' M U2 M' U' M2",
    "R U2 R' U' R' U' R2 U' R2 U2 R2 U2 R'",
    "z2 M2 U2 M2 y' U' M2 U2 M2 U z2",
    "U R2 F2 B2 L2 D' R2 F2 B2 L2",
    "y2 M2 U2 M2 U M2 U2 M2 U",
    "L2 R2 D L2 R2 U2 L2 R2 D L2 R2",
    "R2 U2 R2 U2 R2 U R2 U2 R2 U2 R2",
    "R2 U2 R2 U2 R2 U' R2 U2 R2 U2 R2",
    "x' r R U2 r' R' U' u' R2 u U x",
    "S2 U S2 U2 S2 U S2",
    "l2 U2 l2 U2 l2 U2 l2 U2 l2 U2 l2 U l2 U2 l2 U2 l2 U2 l2 U2 l2 U2 l2",
    "U' M2 U2 M2 U M2 U2 M2",
    "R U' R U R U R U' R' U' R2 y R U' R U R U R U' R' U' R2 y'",
    "R L D2 R' L' U R L D2 R' L'",
    "R U R' U' L' U' L U2 R U' R' U' L' U L y' M2 U M U2 M' U M2",
    "r' R' f2 r R U r' R' f2 r R U",
    "M' U2 M2 U2 M U M' U2 M2 U2 M",
    "U' M2 U2 M2 U' M2 U2 M2 U2",
    "M' U' M' U2 M' U' M' U2 M' U' M' U2 M' U' M' U2 M' U' M' U2 M' U' M' U2",
    "R' E R u' R' E R u' R' E R u' R' E R u' R' E R u' R' E R u'",
    "y' M2 U' M2 U2 M2 U' M2",
    "y M2 U' M2 U2 M2 U' M2",
    "y2 M2 U' M2 U2 M2 U' M2",
    "L2 F2 L2 F2 L2 F2 u2 L2 F2 L2 F2 L2 F2 u2 L2 F2 L2 F2 L2 F2",
    "L2 F2 L2 F2 L2 F2 U2 L2 F2 L2 F2 L2 F2 U2 L2 F2 L2 F2 L2 F2",
    "R2 F2 R2 F2 R2 F2 U2 R2 F2 R2 F2 R2 F2 U2 R2 F2 R2 F2 R2 F2",
    "R2 U' R' U' R U R U R U' R U R2 U' R' U' R U R U R U' R U'",
    "S R' U2 R2 U2 R2 U2 R' S'",
    "U R2 U2 R2 U2 R2 U' R2 U2 R2 U2 R2",
    "U M2 U2 M2 U' M2 U2 M2",
    "U M2 U M2 U M2 U M2 U M2 U M2 U2",
    "M2 U M2 U M2 U2 M2 U M2 U M2",
    "M2 u M2 u2 M2 u M2",
    "M2 E2 S2 M2 D M2 D2 M2 D M2 S2 E2 M2",
    "M2 U2 M2 U M2 U2 M2 U'",
    "M2 U2 M2 U' M2 U2 M2 U'",
    "M2 U' M2 U' M2 U' M2 U' M2 U' M2 U'",
    "M' U M U2 M' U M U' M' U M U2 M' U M U'",
    "S2 D M2 U2 M2 U2 D' S2",
    "U2 M2 U M2 U M2 U M2 U M2 U M2 U",
    "U R2 F2 B2 L2 D R2 F2 B2 L2",
    "R U2 R2 U2 R2 U2 R' S R2 S'",
    "M' U M U2 M' U M U' M' U M U2 M' U M U",
    "M2 U' M2 U' M2 U' M2 U' M2 U' M2 U",
    "M2 U M2 U M2 U M2 U M2 U M2 U'",
    "M2 U M2 U M2 U M2 U M2 U M2 U",
    "R2 F2 D2 L2 B2 L2 B2 L2 B2 D2 F2 R2",
    "M2 U2 M2 U M2 U2 M2 U",
    "R U R2 F' R U2 R U' R' U' R' F R2 U R' U' R U' R'",
    "R U R' U2 R U' R' U' R U' R' U2 R U' R' U' R U2 R'",
    "R' U2 R2 U2 R2 U' R2 U' R' U' R' U2 R",
    "M' U M2 U2 M2 U M2 U2 M' U2"
  ],
  "Aa": [
    "l' U R' D2 R U' R' D2 R2 x'",
    "R' F R' B2 R F' R' B2 R2",
    "R' B' R2 D R' U' R D' R' U R' B R",
    "R' D R U2 R' D' R U' R' D R U' R' D' R",
    "R' F R' f2 r U' r' f2 R2",
    "F U R2 D R' U' R D' R' U R' U' F'",
    "R' D' R U2 R' D R U' R' D' R U' R' D R",
    "R' F R' f2 L F' L' f2 R2",
    "l' U R' D2 R U' R' D2 R l",
    "R' U' R U' R' U R' D' R U' R' D R2 U R' U R",
    "x' U2 R2 U' L' U R2 U' L U' x",
    "B2 D B2 D' R2 B2 U' B2 U R2",
    "F U2 R' D' R U' R' D R U' F'",
    "U' r U r' U' r' F r2 U' r' U' r U r' F'",
    "R2 D R' U2 R D' R' U2 R' F R' F' r U R U' r'",
    "R' U2 R2 U' L' U R' U' L U R' U2 R",
    "U' r' F R F' r U2 R' U' R U R' U R U R U2 R' U' R U' R' U R'",
    "R D R' U' R D' R' U2 R D R' U' R D' R'",
    "U' r U r' U' r' F r2 U' r' U' r U r' F' U2",
    "U2 R' D' R U' R' D R U' R' D' R U2 R' D R U2",
    "B2 R2 B' L' B R2 B' L B'",
    "Lw' U R' D2 R U' R' D2 R Lw",
    "x' R' D R' U2 R D' R' U2 R2 x",
    "U' R U R' U' R U R D R' U R D' R' U2 R' U R U' R'"
  ],
  "Ab": [
    "R' B' R U' R D R' U R D' R2 B R",
    "l' R' D2 R U R' D2 R U' l",
    "R2 B2 R F R' B2 R F' R",
    "F U R U' R D R' U R D' R2 U' F'",
    "R' D' R U R' D R U R' D' R U2 R' D R",
    "R' F' R U R U' R2 F R U R' F' R F",
    "x' R2 U2 R D R' U2 R D' R x",
    "U' L F' L B2 L' F L B2 L2",
    "l' U' l U l F' l2 U l U l' U' l F",
    "R' D R U R' D' R U R' D R U2 R' D' R",
    "F U R' D' R U R' D R U2 F'",
    "l' U' l U l F' l2 U l U l' U' l F U'",
    "l' R' D2 R U R' D2 R U' R x'",
    "R2 f2 r U r' f2 R F' R",
    "R2 D' R2 U R2 U' D R2 U R2 D' R2 D",
    "x' U L' U R2 U' L U R2 U2 x",
    "x' l2 D2 R U R' D2 R U' l",
    "F R' F' r U R U' r' R2 D R' U2 R D' R' U2 R' r U R' U' r' F R F'",
    "y2 z2 y2 z2 F U R' D' R U R' D R U2 F'",
    "L' R' D2 R U R' D2 R U' L",
    "R' U2 R U' L' U R U' L U R2 U2 R",
    "B L' B R2 B' L B R2 B2",
    "B L3 B R2 B3 L B R2 B2",
    "U R' D R U R' D' R U2 R' D R U R' D' R U'",
    "L' U' L F l' U' L U l F' L2 U L"
  ],
  "E": [
    "R2 U F' R' U R U' R' U R U' R' U R U' F U' R2",
    "r U R U' r' F R' F' r U R' U' r' F R F'",
    "L U' R D2 R' U R L' U' L D2 L' U R'",
    "R2 U R' U' y R U R' U' R U R' U' R U R' y' R U' R2",
    "R' U' D' R' D F D' R U D R U' R' F' R",
    "F U' R U' R U R' U R U2 R' U R' U' R U2 R' F'",
    "F' r U R' U' r' F R U2 r U R' U' r' F R F'",
    "R2 U R2 U D R2 U' R2 U R2 U' D' R2 U R2 U2 R2",
    "R' D' R U' R' D R U R' D' R U R' D R U R' D' R U' R' D R U'",
    "L F R F' L' F R' F' L F R' F' L' F R F'",
    "F R' U' R U' R' U2 R U' R U R' U2 R U R' U F'",
    "R' U L' D2 L U' R L' U R' D2 R U' L",
    "R U' L D2 L' U R' L U' R D2 R' U L'",
    "F U' R U' R' U2 R U' R' U R' U2 R U R' U R F'",
    "R2 U2 F' R' U' R U R' U' R U R' U' R U F U2 R2",
    "U' R' U' R' D' R U' R' D R U R' D' R U R' D R2",
    "U R' U' R' D' R U' R' D R U R' D' R U R' D R2 U'",
    "L U' R D2 R' U L' U2 L U' R D2 R' U L' U2",
    "R' U' R' D F D' R U D R U' R' F' D' R",
    "L2 U2 F U L U' L' U L U' L' U L U' L' F' U2 L2",
    "L2 U2 F L U L' U' L U L' U' L U L' U' F' U2 L2",
    "z U2 R2 F R U R' U' R U R' U' R U R' U' F' R2 U2 z'",
    "R U2 R2 D R2 U2 R B2 U R2 U R2 U2 B2 D' R2",
    "U R U R' U' R' F R2 U' R' U' R U R' F' U2 R U R' U' R' F R2 U' R' U' R U R' F'",
    "z U2 R2 f R U R' U' R U R' U' R U R' U' f' R2 U2 z'",
    "R' F' L' F R F' L F L' U' L U R U' L' U L R'",
    "R' U2 F' U F U2 R U R2 U' F' U F R U' R",
    "U R' U' R' D' R U' R' D R U R' D' R U R' D R2",
    "R U' r F2 r' U R' U2 R U' r F2 r' U R'",
    "R' U L' D2 L U' R U2 R' U L' D2 L U' R",
    "L U' R D2 R' U L' U2 L U' R D2 R' U L'",
    "F R' F' r U R U' r' F R F' r U R' U' r'",
    "y l' U R D' R' U' R D y' z r U R' U' r' F R F'",
    "U x' R U' R' D R U R' D' R U R' D R U' R' D' x U'",
    "F R' F' r U R U' r2 U' R U r f' U' f"
  ],
  "T": [
    "R U R' U' R' F R2 U' R' U F' L' U L",
    "R2 u R2 u' R2 F2 u' F2 u F2",
    "R2 U R2 U' R2 U' D R2 U' R2 U R2 D'",
    "F R U' R' U R U R2 F' R U R U' R'",
    "R2 U R2 U' R2 F2 U' F2 D R2 D'",
    "R2 U R2 D' F2 L2 U' L2 D F2",
    "R2 U R2 D' F2 r2 D' r2 D F2",
    "R U R' U' R' F R2 U' R' U F' r' F r",
    "R2 D B2 D' R2 F2 D' L2 D F2",
    "R U R' U' R' F R F' R' F R F' U' F' U F",
    "R U R' U' R' F R2 U' R' F' U L F' L' F",
    "R U R' U' R' F R R U' R' U' R U R' F'",
    "R2 U' R2 U R2 U D' R2 U R2 U' R2 D",
    "F R U' R' U R U R' l' U' l U R U' R'",
    "S' R U R' U' R' F R2 U' R' U' R U R' F' U2 S",
    "R2 u R2 u' R2 F2 u' F2 u F2 U'",
    "R U R' U' R' F R F' U F' r U r' U' r' F r U2",
    "D' R2 U R2 U' R2 U' D R2 U' R2 U R2",
    "U F2 U' F2 D R2 B2 U B2 D' R2",
    "B2 R B R' B L B L B2 L B2 L' B2 R B2 R' B' L'",
    "R D' R U' R' D R U R U R U' R' U' R U' R' U R",
    "R U R' U' R2 D R' U' R' U' R U R2 D' R"
  ],
  "F": [
    "R' U R U' R2 F' U' F U R F R' F' R2",
    "R' U R U' R2 F' U' F U R F R' F' R2 U'",
    "R U R' U' R' U R U2 L' R' U R U' L U' R U' R'",
    "l U' L F2 l' F M' L F2 L2 U' M",
    "R U2 R U R' D R D' R U' D R2 U R2 D' R' U R'",
    "R U R' U' R' U R U2 R' L' U R U' r x' U' R U' R'",
    "U R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R U'",
    "U R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    "R U R' U' R' U R U2 R' L' U R U' L U' R U' R'",
    "F' U R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R U' F",
    "M' U2 r U' R x' U2 r' U M R U2 R2 x",
    "R F' R B2 R' F R U' R2 U R2 U B2 D' R2 D",
    "R' U R U' R2 y' R' U' R U y x R U R' U' x' R2 U'",
    "R U R' f' U' R U2 R' U' R U' R' f U R U2 R'",
    "L2 F2 L2 R U R' U' R' F R2 U' R' U' R U R' F' L2 F2 L2",
    "R' U2 R2 D R' U' R D' R' U2 R' U R2 U2 R' U' R U' R'",
    "f U' F R U R' U' R' F' U2 F U' R' U' R U f' F'",
    "R U' R' U R f R' U R U' R' U R U' R f' U R'",
    "U R U R' U' R' F R2 U' R' U' R U R' F' M2 U M2 U2 M2 U M2",
    "R2 U' R' U' R U R' D R D' R U' D R2 U R2 D' U R2"
  ],
  "Ja": [
    "L' U' L F L' U' L U L F' L2 U L",
    "R U' L' U R' U2 L U' L' U2 L",
    "L' U2 L U L' U2 R U' L U R'",
    "L' R' U2 L U L' U2 R U' L",
    "R' r' F2 r U r' F2 R F' r",
    "U2 F U' R' F R2 U' R' U' R U R' F' R U R' F' U'",
    "r' R' F2 r U r' F2 R F' r",
    "R U R' F R' F' R' D R' U' R D' R2 F' U2 F",
    "U2 r D r' U2 r D' r' U' r D r' U' r D' r'",
    "U' r2 U D' r2 U' r2 D r2 D' r2 D r2 U",
    "R U' r' F R' F2 r U' r' F2 r",
    "U2 R2 x F R F' R U2 r' U r U2 x' U'",
    "B' U F' U2 B U' B' U2 B F",
    "l F' r' x F l' U2 L U' L' U2 L",
    "U2 F U' R' F R2 U' R' U' R U R' F' R U R' F'",
    "U R2 D' F' R U' R' F D R' f' U' f",
    "L' U2 L U L' U2 l F' L F l'",
    "r' F' r F r' F' r U r U' r2 F r",
    "x r' U' r U r' U' L U r U' r2 F r",
    "z U' R2 U R U' R2 D R' U R D' z'",
    "z D R' U' R D' R2 U R' U' R2 U z'",
    "z R' U' R D' R2 U R' U' R2 U D z'",
    "L2 D L D' L B2 R' U R B2",
    "L' U' L F L' U' L U L F' L2 U L U",
    "U R B' R F2 R' B R F2 R2 U R U' R U R U R U' R' U' R2",
    "U2 R' U2 R U R' U2 L U' R U L' U'",
    "U2 x R2 F R F' R U2 r' U r U2 x' U'",
    "U R D' R U' R' U' R U R' F' R U R' U' R' F R D R'",
    "U R' U' R2 B R' U' R' U R B' R' U R U'",
    "U R' U L' U2 R U' R' U2 R L U'",
    "B2 R' U' R B2 L' D L' D' L2 U",
    "L' U' L F L' U' L U L F' L2 U L U2",
    "U2 x R2 U R U2 r' U r U x' U' R U",
    "l F' L' F l' U2 L U' L' U2 L",
    "R' L' U2 L U L' U2 R U' L",
    "U r D r' U2 r D' r' U r D r' U r D' r'",
    "f' r U' r2 U r' F' r2 F B z"
  ],
  "Jb": [
    "R U2 R' U' R U2 L' U R' U' L",
    "r' F R F' r U2 R' U R U2 R'",
    "L' U R U' L U2 R' U R U2 R'",
    "R U2 R' U' R U2 r' F R' F' r",
    "R U' F U' R' U' R U F' U2 R'",
    "r2 U R' U R' U' R U' r2 D R U R U' R' D'",
    "L R U2 R' U' R U2 L' U R'",
    "B2 U B U B' U' B2 D B D' B' D' R2 D R2",
    "z U' R D R' U R2 D' R D R2 D' z'",
    "U R U R2 F' R U R U' R' F R U' R'",
    "U2 r' D' r U' r' D r U2 r' D' r U' r' D r",
    "R2 D' R' D R' B2 L U' L' B2",
    "R U R' F' R U R' U' R' F R2 U' R' U'",
    "R U2 R' U' R U2 L' U R' U' r x'",
    "R U R2 D' R2 U R' U' R2 D R' U' R'",
    "R U' R' U2 R' D' R U R' D R U R U' R' U' R U' R'",
    "R U2 R3 U3 R U2 L3 U R3 U3 L U",
    "R2 D B2 D' B2 U B2 U' B2 R2 U'",
    "r' D r U r' D r U' r' D r U r' D r U' r' D r",
    "U R U' L U2 R' U R U2 R' L'",
    "U' L U' R U2 L' U L U2 R' L' U'",
    "L l F2 l' U' l F2 L' F l'",
    "R U l' U' l U R' U' l' U l R U' R'",
    "L' U R U' L U U R' U R U2 R'",
    "R U' L' U2 R' U' L U R U' R' U2 L' U L R U2 R' U' R U' R'",
    "R U2 R' U' R U2 L' U R' U' r x' U",
    "R U R' U' R' F R2 U' R' U' R U R' F' M2 U M U2 M' U M2",
    "R' U R' D2 R U' R' D F2 R' F2 U' R U F2 D R' U",
    "R U2 R' U' R U2 z U' R D' R' U z'",
    "R U2 R' U' R U2 L' U R' U' L U",
    "L' U R U' L U2 R' U R U2 R' U",
    "l F l' F' l F l' U' l' U R2 x' U' R'",
    "r' D r U2 r' D' r U r' D r U r' D' r",
    "F R' F' R2 r D r' U' r D' R' r' F' U' F",
    "R2 U R2 D' R2 D B2 U' B2 R2",
    "f R' F R2 B' R B R2 f' F'"
  ],
  "Ra": [
    "L U2 L' U2 L F' L' U' L U L F L2",
    "R U R' F' U' F R U R' F R' F' R2 U2 R'",
    "U2 R U2 R' U' R' F' R U2 R U2 R' F R U' R'",
    "R U2 R2 F R F' R U' R' F' U F R U' R'",
    "U R f' U' f U' R' U' F' U' F R f R2 f'",
    "L U2 L' U2 L F' L' U' L U L F L2 U",
    "U R U' R' U' R U R D R' U' R D' R' U2 R' U'",
    "U R U R' F' R U2 R' U2 R' F R U R U2 R' U2",
    "L U2 L' U2 L F' L' U' L U L F L2 U2",
    "U R U' R' U' R U R' U R' D' R U' R' D R2 U R' U'",
    "U R U' R' U' R U R D R' U' R D' R' U2 R'",
    "L U2 L D L' U L D' L' U' L' U L U L'",
    "U' r U2 R' U' R U' r' F U R U' R2 F' r U R U' r'",
    "L U R' D R U R' D' R L' U L U L'"
  ],
  "Rb": [
    "R' U2 R' D' R U' R' D R U R U' R' U' R",
    "U R2 F R U R U' R' F' R U2 R' U2 R",
    "U' L' U L U L' U' L U' L D L' U L D' L2 U' L",
    "R' U2 R U2 R' F R U R' U' R' F' R2 U'",
    "U R U R' U' R' F R2 U' R' U' F' L' U L U F U R U' R' F' U2",
    "M U2 M' U' R U R' F' R U R' U' R' F R2 U' R' M U2 M'",
    "R' U R' B2 R U' R' B2 R2 U M U2 M'",
    "U' L' U L U L' U' L U' L D L' U L D' L2 U' L U'",
    "R' U' L D' L' U' L D L' R U' R' U' R"
  ],
  "Ga": [
    "R2 u R' U R' U' R u' R2 F' U F",
    "D' R2 U R' U R' U' R U' R2 U' D R' U R",
    "r U2 R U' r' F U R' U' F' r U' r'",
    "R2 D B' U B' U' B D' R2 F' U F U'",
    "F R U' R' U R U R2 F' U2 R U R U' R2 U2 R",
    "R2 U R' U R' U' R U' R2 U' D R' U R D'",
    "R' F R' U R U' F' R2 U2 R' U R2 U R2 U R",
    "R U R2 F' R U R U' R' F R' F' r U R U' r' F R U' R'",
    "R l f R' F l' U' R u' R2 F' U F",
    "R2 F2 R' U R2 F' R U R U' R' F R U' R F2 R2",
    "U R D L' D2 R D' L' F2 D' L2 D' R2",
    "F f R2 F' f' L' U R' U2 L U' R U",
    "F2 R2 B2 D B R2 D' F' R2 B U R2 F'",
    "R L U2 R' L' B2 U F2 U' F2 D R2 D' B2 U",
    "y u' R2 U R' U R' U' R U' R2 U' D R' U R"
  ],
  "Gb": [
    "R' U' R U D' R2 U R' U R U' R U' R2 D",
    "R U R' F' R U R' U' R' F R U' R' U2 R U R U' R2 U2 R",
    "U r U r' F U R U' F' r U R' U2 r'",
    "R' F' R U R U R' U' R U' R' F R U R' U R U R' U' R U' R'",
    "R' U2 R2 U R' U' R' U2 F R2 U' R' U' R U R' F'",
    "R' U' R B2 D L' U L U' L D' B2",
    "R2 U' R2 U' R2 U2 R2 U2 B2 U B2 U B2 U2 B2 U'",
    "U F' U' F R2 u R' U R U' R u' R2",
    "R2 D L2 D F2 L D R' D2 L D' R' U'",
    "U2 R' U2 R U' F R U R' U' R' F' U' R U R U' R'",
    "U R2 F' B' L2 F' B D' L2 F2 U L2 U' R2 U L2 B2",
    "U2 R U R' U2 R' D' R U' R' D U' R2 U' R' U R' U R",
    "U R2 F2 U F U F' R2 F U' F' R2 U' F2 R2",
    "R U R' F' R U R' U' R' F R2 U' R U' S' U2 S U' R2",
    "B F U2 B F' U' B2 L2 U' L2 U F2 U' B2 U F2 L2 B2"
  ],
  "Gc": [
    "D R2 U' R U' R U R' U R2 D' U R U' R'",
    "R2 u' R U' R U R' u R2 f R' f'",
    "R D' R2 U' R2 U R' U R U2 R' U R' U R2 D R'",
    "R U R' U R U2 R' U R U2 R' U2 L' U R U' R' L",
    "R2 u' R U' R U R' u R2 B U' B'",
    "R2 u' R U' R U R' u R l d l' f'",
    "z R' F' B' R2 F B R' U R' D R2 U' R D' z'",
    "R F R' U R' U' R' U R U' R' F' U' R U R' U' R2",
    "F R' F' R F R' F' R F R' F' R U2 R2 U2 R2 U' R2 U' R2",
    "U2 R2 F2 R U2 R U2 R' F R U R' U' R' F R2",
    "R2 u' R U' R U R' u R2 f R' f' U",
    "R2 u' R U' R U R' u R2 B U' B' U",
    "R2 F' R D R' U' R' U' R U2 R' U' R2 D' R' F R2",
    "R' D' R' U' R D U' R D' U R' U R D R U R U' R'",
    "R F' R2 F' U' R U' R' U2 R U' R' F R2 F R'",
    "R U' F u' R' U' R u D U' R' U2 R D' U F' R'",
    "R' U' F2 u' R U R' u F2 R U' F R U R' U' F'",
    "R' U' R U' R2 D R' U R D' R U R U' R U' R'",
    "R2 U' R U' R U R' U R' F' R' U R U' F R'",
    "R2 u' R U' R U R' u R U2 F' U' F R",
    "R2 u' R U' R U R' u R U R' F R F' U' R",
    "R2 F' R D R' U' R' U' R U2 R' U' R2 D' R' F R2 U2",
    "R2 U' R U' R U R' U R2 U D' R U' R' D"
  ],
  "Gd": [
    "D' R U R' U' D R2 U' R U' R' U R' U R2",
    "R U R' F' R U R' U R U' R' U' R' F R2 U R' U' R U' R'",
    "f R' F R2 f' U F' R' L' U2 L R",
    "y R U' L U2 R' U L' y' R' L' U2 L R U",
    "R2 U R2 U R2 U2 R2 U2 F2 U' F2 U' F2 U2 F2 U",
    "R U R' F2 D' L U' L' U L' D F2",
    "U R U R' U' R' F R2 U' R' F R U' R' U' R U R' F' R U R' F'",
    "R F' U R' U' R F R U' R U' R' U R' U R2",
    "M' U2 M L' U' L F L' U' L U L F' L2 U L M' U2 M",
    "R U R' D U' R2 U' R U' R' U R' U R2 D'",
    "R2 U' R' U' R U R U R2 U R' U' R' D' R U R' D R U2 R",
    "R U R' F' L' U' L U L F' L' F2 R U R' U' L' U2 R U R' U2 L",
    "R U R' F' R U2 R' U' R U R' U2 R' F R U R U' R' U R U2 R'",
    "R' U' F' R U R' U' R' F R2 U' R' U R U R U R' U R U2 R' U'",
    "y u' R U R' U' D R2 U' R U' R' U R' U R2"
  ],
  "V": [
    "R' U R U' R' f' U' R U2 R' U' R U' R' f R",
    "R2 D' R2 U R2 D U' R D' R D R' U R U' R",
    "R' f' R U R' U R U2 R' U f R U R' U' R",
    "R' U R' U' R D' R' D R3 U D' R2 U' R2 D R2",
    "R' U2 R U2 L U' R' U L' U L U' R U L'",
    "R U2 R' D R U' R U' R U R2 D R' U' R D2",
    "U R U' R U R' D R D' R U' D R2 U R2 D' R2",
    "U F' U F' U' R' F' R2 U' R' U R' F R F",
    "R2 D' R2 U R2 U' D R D' R D R' U R U' R",
    "U R2 D R2 U' R2 U D' R' D R' D' R U' R' U R'",
    "R2 U' f2 D f2 R D' R D R' U R U' R",
    "R U D' R U' R U R' U' D R D' R D R2 U R'",
    "R U R' U R' U' F' R U R' U' R' F R2 U' R' U' R U R U' R' U R' U R",
    "D2 R U2 R' D R U' R U' R U R2 D R' U' R",
    "R' B' D R D' R D R2 D' R f z' R U R' U' R",
    "R U' R F2 R' U R' U' R2 U' F2 U F2 D' F2 D R2",
    "R2 U' B2 U B2 R D' R D R' U R U' R",
    "U' F R U' R' U' R U R' F' R U R' U' R' F R F' M2 U M2 U2 M2 U M2 U'",
    "R' U R' U' x z' x R' U R' U' l R U' R' U R z l",
    "R' U R' U' y R' D R' D' R2 y' R' B' R B R",
    "M' U2 M F R' F R2 U' R' U' R U R' F' R U R' U' F' M' U2 M",
    "x R' U R' D2 R U' R' D2 F R F' R U2 r' U r U2 x'",
    "R' f' U' f U' f R f2 U f U R U' R",
    "U R2 U F2 U' F2 R' D R' D' R U' R' U R'",
    "R' U R' U' B' R' B2 U' B' U B' R B R",
    "f R2 f' M' U2 R' U' R2 U R' U' R' F R F' U' M",
    "R' U R' U' f' U' f2 R' f' U f' U f R",
    "D R U2 R' D R U' R U' R U R2 D R' U' R D",
    "M' U2 M F R U' R' U' R U R' F' R U R' U' R' F R F' M' U2 M"
  ],
  "Y": [
    "F R' F R2 U' R' U' R U R' F' R U R' U' F'",
    "R2 U' R2 U' R2 U F U F' R2 F U' F'",
    "F R' F' R U R U' R2 U' R U R f' U' f",
    "R2 U' R2 U' R2 U R2 D' R2 U R2 U' R2 D R2",
    "R' f' U F R' U' R f R F' R2 U R2",
    "U' B' R B R' U' R' U R2 U R' U' R' F R F'",
    "R' U' R U' R U R' F' R U R' U' R' F R2 U' R2 U R",
    "R2 U' R2 U' R2 U R' F' R U R2 U' R' F R",
    "R2 D' R2 U R2 U' D R D' R D R2 U' R' U R U R2",
    "R2 D' R2 U R2 U' R2 D R2 U' R2 U R2 U R2",
    "R' U' R2 U R2 F' R U R U' R' F R U' R' U R' U R",
    "R' F R F' U' F' U F U' R U R' U' R' F R F'",
    "F R F' U r' D' r U' r' D r2 U R' U R U2 r' U' R'",
    "F U F' R2 F U' F' U' R2 U R2 U R2",
    "F R U r U2 R2 F R F' R U2 r' R' F'",
    "R' F' R' F2 r2 U' r' F r' F2 R U' F R",
    "R' U' R F2 R' U R U F2 U' F2 U' F2",
    "R' U' R F2 R' U R D R2 U' R2 D' F2",
    "R' F R F' U' R U' R' U F R' F' R2 U R' U' R' F R F'",
    "F2 U F2 U F2 U' R' U' R F2 R' U R",
    "F R' F' R U R U' R' U2 L' U' L U L F' L' F U'",
    "R2 F R F' U' R U' R' U R2 U R' U' R' F R F'",
    "R' F' U F U F' U' R' U' R F R' U R2",
    "F2 D R2 U R2 D' R' U' R F2 R' U R",
    "F R' F' R U R U' R' F R U' R' U R U R' F'",
    "y' R2 u R2 U R2 D' R' U' R F2 R' U R",
    "F R' F' R U R U' R2 U' R U R B' R' B",
    "R' F' U L' U2 R U' R' U2 L R U' R' F R",
    "R' F' R U R' L' U2 R U R' U2 L U' F R",
    "R' F' R U R' U F2 r U r' U' r' F r F U' F R",
    "F U R U' R' F' U2 R U2 R' U' R U' R2 F2 r U r' F R",
    "R' U' R U' R U2 R' U' R U2 L' U R' U' L U R' U R"
  ],
  "Na": [
    "F' R U R' U' R' F R2 F U' R' U' R U F' R'",
    "R F U' R' U R U F' R2 F' R U R U' R' F",
    "r' D r U2 r' D r U2 r' D r U2 r' D r U2 r' D r",
    "z U R' D R2 U' R D' U R' D R2 U' R D' z'",
    "L U' R U2 L' U R' L U' R U2 L' U R'",
    "r' D' r U' r' D r U r' D' r U r' D r U r' D' r U' r' D r",
    "R U' R2 B2 D' L F2 L' D B2 R2 U R'",
    "l D F' l' U l F D' l2 U' l U l F' l' F",
    "R U' R' U R f R f' R' U' R f' U f R' U R'",
    "R F R' F' R U R' U' R' F R2 U' R' U' R U F' R'",
    "L U' L' U L F U F' L' U' L U L' U f' L' f",
    "U' F' U F2 R2 U F' R2 F U' R2 F2 U' F",
    "r' D' r U r' D r U' r' D' r U2 r' D r U r' D' r U' r' D r",
    "L D L' F' R U R' U' R' F R2 U' R' U' R U R' L D' L'",
    "R2 D' R2 U R U R' U' R' F R2 U' R' U' R U R' F' U' R2 D R2",
    "U' F2 U2 R2 U F2 U2 F2 R2 U R2 U2 R2 F2",
    "z' D L' U L2 D' L U' D L' U L2 D' L U' z",
    "r' D r U2 r' D' r U' r' D r U r' D' r U r' D r U r' D' r",
    "L U' L' U L F U F' L' U' L F' L F L' U L'",
    "r2 U' r2 U D r2 D' r2 U2 r2 U' r2 U D r2 D' r2",
    "R U' L U2 R' U L' R U' L U2 R' U L'",
    "y R U' R2 B2 D' L F2 L' D B2 R2 U R'",
    "R U R' U r' F R F' r U2 R' U R U2 R' U' R U' R'",
    "L U' R U2 L' U L R' U' R U2 L' U R'",
    "R U' R' U R B U B' R' U' R B' R B R' U R'",
    "R U R' U' R' U' R U F' U' F U' R' U2 F R F'",
    "R' B' R U2 R' B' R U2 R' B' R U2 R' B' R U2 R' B' R",
    "R U R' U R U2 R' U' R U2 L' U R' U' L U' R U' R'",
    "R U R' U R U2 R' U' F R U R' U' F' U r U' r2 U r2 U r2 U' r",
    "F U F' R U R' F' R U R' U' R' F R2 U' R' U' F U' F'",
    "r2 U' r2 U' R U R' U' R' F R2 U' R' U' R U R' F' U r2 U r2 U2",
    "R U R' U2 R U R2 F' R U R U' R' F R U' R' U' R U' R'",
    "L2 U2 F2 U L2 U2 L2 F2 U F2 U2 F2 L2",
    "L U' L F' L' F L' U L F U' F' L' U' L U L'",
    "y' R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    "y2 R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    "y R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    "R U' R' U l U F U' R' F' R U' R U l' U R'",
    "l D F' l' U l F D' l' R' F' R U R U' R' F",
    "l' D l U2 l' D l U2 l' D l U2 l' D l U2 l' D l U2",
    "L U' l F2 L' F l' L U' l F2 L' F l'",
    "r' D' r U2 r' D' r U2 r' D' r U2 r' D' r U2 r' D' r U2",
    "R U' L U2 R' U L' R U' L U2 R' U L' U'",
    "R2 U R2 U' D' R2 D R2 U2 R2 U R2 U' D' R2 D R2 U",
    "z D R' U R2 D' R U' D R' U R2 D' R U' z'",
    "R U R' U F R' F' R2 r D r' U' r D' R' r' F' U' F R U' R'",
    "R' F R2 B' R2 F' R2 B U R' U R U' R' F' r' F' r F",
    "F U' B U2 F' U B' F U' B U2 F' U B' U",
    "y L U' R U2 L' U R' L U' R U2 L' U R' U",
    "r' D' r U r' D r U' r' D' r U' r' D r U' r' D' r U r' D r",
    "R U' L U2 R' U R L' U' L U2 R' U L'",
    "y2 z2 y2 z2 R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'"
  ],
  "Nb": [
    "r' D' F r U' r' F' D r2 U r' U' r' F r F'",
    "R' U L' U2 R U' L R' U L' U2 R U' L",
    "R' U R U' R' F' U' F R U R' U' R U' f R f'",
    "L' U' L U' L' U' L F L' U' L U L F' L2 U L U2 L' U L",
    "R2 U2 F2 U' R2 U2 R2 F2 U' F2 U2 F2 R2",
    "R' U R' F R F' R U' R' F' U F R U R' U' R",
    "z D' R U' R2 D R' U D' R U' R2 D R' U z'",
    "D' R2 D R D' R2 U R' D U2 R' U2 R U2 R",
    "r D r' U2 r D r' U2 r D r' U2 r D r' U2 r D r'",
    "F r' F' r U r U' r2 D' F r U r' F' D r",
    "z U' R D' R2 U R' D U' R D' R2 U R' D z'",
    "l D' l' U2 l D' l' U2 l D' l' U2 l D' l' U2 l D' l' U2",
    "L' F' U L U' L' U' F L2 F L' U' L' U L F'",
    "R' U R2 F2 D r' U2 r D' F2 R2 U' R",
    "R' U' R U2 R F R' U R F' R2 U F U2 F' R",
    "R' U L' U2 R U' R' L U L' U2 R U' L",
    "R' U2 D R' U R2 D' R D R2 U' D' R U2 R",
    "R U' R2 F2 U' R F2 R' U F2 R2 U R'",
    "L' U' L R' U L' U2 R U' R' U2 R L U' L' U L",
    "L' U' L U x R2 F R F' R U2 r' U r U2 x' U' L' U L",
    "B2 D B2 R U R' U' R' F R2 U' R' U' R U R' F' B2 D' B2",
    "R' U2 R2 U R2 U R2 U' D' R U R' D R2 U' R' U' R2 U2 R",
    "r' F' r U l' R' F R F' R U2 r' U r U2 B' r' U L",
    "R' U r' F2 R F' r R' U r' F2 R F' r",
    "R' U' R U L' U' L F L' U' L U L F' L2 U L R' U R",
    "R2 D R' U R D' R2 U' R U' R' U' F R U R' U' R' F' R",
    "D R' U2 R' U2 R U2 D' R U' R2 D R' D' R2",
    "R' F R U F' U' Lw' U L U R U2 r' F' R U' R' U",
    "r' F' r U r R2 F R F' R U2 r' U r U2 r' U' r' F r",
    "F' D R2 F2 U B' R2 B U' F2 R2 D' F",
    "R2 D R' D' R2 U D R' U2 R' U2 R U2 D' R",
    "R2 D R D' R2 U R' U2 D R' U2 R U2 R D'",
    "R' B' U R U' R' U' B R2 B R' U' R' U R f' z",
    "y r' D' F r U' r' F' D r2 U r' U' r' F r F'",
    "y R' U L' U2 R U' L R' U L' U2 R U' L U'",
    "R U' R' d R' U R U' R' F' U F R U R' U' R",
    "L' U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R' U2 R L",
    "L' U' L U' R U R' U' R' F R2 U' R' U2 R U R' F' R U R' U' R' F R F' U2 L' U L",
    "r' U2 F2 r U2 r' U' r' F r U' R U R' U' r",
    "R' U2 D R' U2 R U D' R2 U D R' U' R D' R2",
    "R2 U' R2 U D R2 D' R2 U2 R2 U' R2 U D R2 D' R2",
    "R' U2 R' U D R2 D' R' D R2 U' R U2 D' R",
    "L' U2 L U L U' F' U L U' L' U' F U2 L' U' L2 U2 L",
    "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R' M2 U' M2 U2 M2 U' M2",
    "R' U' R U2 R' U' R2 B R' U' R' U R B' R' U R U R' U R",
    "R' U L' U2 R U' L R' U L' U2 R U' L U",
    "R' U' R U2 R' U L' U2 R U' R' U2 L R U R' U R",
    "L' U' L U R' U2 R U R' U2 L U' R U L' U' L' U L",
    "L B L' U2 L B L' U2 L B L' U2 L B L' U2 L B L' U2",
    "R' U L' U2 R U' R' U2 R L U R' U L' U2 R U' R' U2 R L",
    "f R' f' U R' U R U' R' F' U F R U R' U' R",
    "y2 R F' R' U2 R F' R' U2 R F' R' U2 R F' R' U2 R F' R'",
    "R' U' R U' R2 D R D' R F2 r' F r F2 U R' U R",
    "F L' U' L U L F' L2 F' U L U L' U' F L",
    "U' R U' R2 F2 U' R F2 R' U F2 R2 U R'",
    "R' U R U' R' F' U' F R U R' U' R d' R U R'",
    "L' U' L U' y R' U L' U2 R U' R' U2 R L y' L' U L",
    "L' U' L U' L' U2 L U L' U2 R U' L U R' U L' U L U2",
    "L' U' L U' L' U2 L U L' U2 R U' L U R' U L' U L",
    "B R' U' R U R B' R2 B' U R U R' U' B R",
    "r D' r' U2 r D' r' U2 r D' r' U2 r D' r' U2 r D' r'",
    "R' U' R U2 R' U L' U2 R U' R' U2 R L U R' U R",
    "L' U R' U2 L U' R L' U R' U2 L U' R U",
    "y2 R' U' R U2 R' U L' U2 R U' R' U2 R L U R' U R",
    "y r D r' U2 r D r' U2 r D r' U2 r D r' U2 r D r'",
    "r D r' U2 r D r' U2 r D r' U2 r D r' U2 r D r' U2",
    "R' U' R U L' U2 L U L' U2 R U' L U R' U' R' U R",
    "L' U' L U R2 U' R2 D R2 U' R2 U R2 U D' R2 L' U L",
    "z' U' L D' L2 U L' D U' L D' L2 U L' D z",
    "R2 D R D' R2 U R' D U2 R' U2 R U2 R D'",
    "R D' F R' D2 r D' r' D2 R2 F' R' D R'",
    "R' U2 f' U' R U R' F' R U R' U' R' F R2 U' R' f U2 R",
    "F' U B' U2 F U' B F' U B' U2 F U' B U'",
    "L' U R' U2 L U' R L' U R' U2 L U' R",
    "R' U' R U' R' U2 R U R' U2 L U' R U L' U R' U R",
    "R' U2 R' U2 R U2 D' R U' R2 D R' D' R2 D",
    "r2 U r2 U' D' r2 D r2 U2 r2 U r2 U' D' r2 D r2",
    "R' U' R U' x R2 F R F' R U2 r' U r U2 x' U R' U R"
  ],
  "F2L1": [],
  "F2L2": [],
  "F2L3": [],
  "F2L4": [],
  "F2L5": [],
  "F2L6": [],
  "F2L7": [],
  "F2L8": [],
  "F2L9": [],
  "F2L10": [],
  "F2L19": [],
  "F2L20": [],
  "F2L21": [],
  "F2L22": [],
  "F2L11": [],
  "F2L12": [],
  "F2L13": [],
  "F2L14": [],
  "F2L15": [],
  "F2L16": [],
  "F2L17": [],
  "F2L18": [],
  "F2L23": [],
  "F2L24": [],
  "F2L25": [],
  "F2L26": [],
  "F2L27": [],
  "F2L28": [],
  "F2L29": [],
  "F2L30": [],
  "F2L31": [],
  "F2L32": [],
  "F2L33": [],
  "F2L34": [],
  "F2L35": [],
  "F2L36": [],
  "F2L37": [],
  "F2L38": [],
  "F2L39": [],
  "F2L40": [],
  "F2L41": [],
  "COLL-A1": [
    "R' U' R U' R' U2 R",
    "U R U2 R' U' R U' R'",
    "U R U2 R2 U' R2 U' R2 U2 R U R U R' U R U2 R'"
  ],
  "COLL-A2": [
    "U2 R2 D R' U R D' R' U R' U' R U' R'",
    "R U R' f' U' R U2 R' U' R U' R' f R U' R'"
  ],
  "COLL-A3": [
    "R' U' F' R U R' U' R' F R2 U' R' U R",
    "R U R' F' R U2 R' U2 R' F R2 U' R'",
    "R2 U R' U R' U' R U' R2 U2 D R' U2 R D'",
    "L R' U' R U L' U2 R' U2 R"
  ],
  "COLL-A4": [
    "R' U' R U R' F R U R' U' R' F' R2",
    "U2 R U2 R' U2 L' U R U' L R'",
    "U R U2 R' U2 D R2 U' R U' R' U R' U R2 D'",
    "L' U' L U' L2 D' L U2 L' D L2"
  ],
  "COLL-A5": [
    "R' U L U' R U L'",
    "z D' R U R' D R U' z'",
    "R' U R U' F U R' U' R F' U"
  ],
  "COLL-A6": [
    "R U2 r' F R' F' r U' R U' R'",
    "R U R' F' R U2 R' U' R U' R' F R U' R'",
    "U' R D R' U R D' R' U2 R' U' R U2 R' U' R",
    "F R U R' U' R' F2 R U2 R U2 R' F",
    "L' U' L U' l F' L' F l' U2 L",
    "L' U' L U' R U' L' U R' U2 L",
    "R U2 L' U R' U' L U' R U' R'",
    "L' U' L F L' U' L U' L' U2 L F' L' U L"
  ],
  "COLL-S1": [
    "R U R2 U' R2 U R' S R2 S'"
  ],
  "COLL-S2": [
    "L' U2 L U2 R U' L' U L R'",
    "R U R2 F' R U2 R U2 R' F R U' R'",
    "M L' U2 L U2 L F' L' F M'",
    "R' U R U2 R' U R2 D R' U R D' R'",
    "U' R' U2 R U2 D' R2 U R' U R U' R U' R2 D",
    "F R' U' R2 U' R2 U2 R2 U' R' F'"
  ],
  "COLL-S3": [
    "L2 D' L U2 L' D L2 U L' U L",
    "R2 F R U R U' R' F' R U' R' U R",
    "R2 U' R U' R U R' U R2 U2 D' R U2 R' D"
  ],
  "COLL-S4": [
    "R U R' U' R' F R F' r U R' U R U2 r'",
    "L F' U2 F L' F' L U2 L' F",
    "r U R' U' r' F R F' R U R' U R U2 R'"
  ],
  "COLL-S5": [
    "R U' r' F R' F' r",
    "l F' L' F l' U' L",
    "z D R' U' R D' R' U R z'"
  ],
  "COLL-S6": [
    "F' R U2 R' U2 R' F2 R U R U' R' F'",
    "F R U' R2 U2 R U R' U R2 U R' F'",
    "R' F R f' U R U R' U2 f R' F' R",
    "L U L' U R' U L U' R U2 L'",
    "R' U2 R U R' U' R F U' R' U' R U F'",
    "R' U R U2 R' U R U2 R D R' U' R D' R'",
    "R U R' U f' U' R U2 R' U' R U' R' f U R U R'"
  ],
  "COLL-L1": [
    "R' U' R U' R' U2 R U' R U R' U R U2 R'",
    "U' R U2 R' U' R U R' U' R U R' U' R U' R'"
  ],
  "COLL-L2": [
    "y' r D r' U r D' r' U y R U2 R'",
    "R U R' U2 L U' R U L' U R'"
  ],
  "COLL-L3": [
    "U2 R U2 R2 D' R U' R' D R2 U' R'",
    "R' F' R U R' U' R' F R2 U' R' U2 R",
    "R' D' r U2 r' D R U2 R U R'"
  ],
  "COLL-L4": [
    "R U R' U' R' F R U R U' R' F'",
    "x' R U' R' D R U R' D' x",
    "l U' R' D R U R' D' x"
  ],
  "COLL-L5": [
    "r U R U' r' F R' F'",
    "U' F R U' R' U' R U2 R' U' F'",
    "L R' U' R U L' U' R' U R",
    "L F R F' L' F R' F'"
  ],
  "COLL-L6": [
    "U' R' U' R U R' F' R U R' U' R' F R2",
    "F R U R' U' R U' R' U2 R U2 R' U' F'"
  ],
  "COLL-U1": [
    "R U R' L' U' L U' L' U2 L R U R' U R U R'",
    "R U R' U' R U R' U' R U R' U' R2 U R2 U R2 U2 R2"
  ],
  "COLL-U2": [
    "L F' L' U L U L' U' L F L' U' L U L F' L' F L'",
    "R U' R' U F' r U' r' F2 R' F R F'",
    "R' F R U r U2 R2 F R F' R U2 r' R' F' R",
    "U' R' U R U D' R U R' U' R U' R' D R2 U' R' U R2",
    "R U' R2 U' R2 U F U F' R2 F U' F' R",
    "R' F U F' R2 F U' F' U' R2 U R2 U R'",
    "R U' R' U F' r U' L' U2 R' U R U' x'",
    "R' F R' F R2 U' R' U' R U R' F' R U R' U' F' R",
    "L' U L U' F R' F R F2 L F' L' F",
    "R2 F' R U R2 U' R' F R U' R2 U R2 U R'"
  ],
  "COLL-U3": [
    "R U' R' U' R U2 R' U' R' D' R U2 R' D R",
    "R' U R U R' F' R U R' U' R' F R2 U' R' U' R",
    "L2 D L' U2 L D' L' U2 L'",
    "R' U' R U' R' U2 R2 U' L' U R' U' L",
    "R' U2 R U R2 F' R U R U' R' F R",
    "x' R U' R' D R U2 R' D' R U' R' x",
    "R' U L' U R U' L U2 R' U R"
  ],
  "COLL-U4": [
    "R U R' U' R' F2 R2 U' R' U' R U R' F2",
    "R' U2 R F' R' F U2 F' R F"
  ],
  "COLL-U5": [
    "R2 F' R U R' U' R' F R' U' R2 U2 R2 U R' U R",
    "L U' R U' L' U R' U2 L U' L'"
  ],
  "COLL-U6": [
    "R' U2 R F U' R' U' R U F'",
    "R U' R' U' R U R D R' U R D' R2",
    "R' U2 R U2 R' F' R U R' U' R' F R2",
    "R' D R2 U' R' U' R U2 R2 D' R",
    "U' F E R U R' U' E' F' U M' U2 M",
    "M U' M' F R U R' U' F' M U M'",
    "R U' R' U' R U2 R2 D' R U R' D R"
  ],
  "COLL-T1": [
    "R U2 R' r' F2 r U' R U' R' U' r' F r",
    "R U2 R' U' R U' R' U R U R' U R U2 R'",
    "u2 R U' R2 U' R U' R U R' U R U R' U' R' U R u2",
    "R U2 R' L' U2 L U L' U L U R U' R'"
  ],
  "COLL-T2": [
    "R' U R U2 r' R' F R F' r",
    "R' U2 R U R2 F R U R U' R' F' R",
    "R' U' R' U' R U R' F' R U R' U' R' F R'",
    "R' U R U2 L' R' U R U' L",
    "R' U L' U' L R U2 L' U' L",
    "L U' L' U2 L R U' L' U R'",
    "L' U2 L U L' U L U' L' U R U' L U R'",
    "R U2 R' U' R' F R2 U' R' U' R U R' F' R U' R'"
  ],
  "COLL-T3": [
    "B' R' F R B R' F' R",
    "x' U' R' D R U R' D' R x",
    "L' U' L' D' L U L' D L2",
    "x D' R' U R D R' U' l"
  ],
  "COLL-T4": [
    "R' D' R U R' D R U2 R U2 R' U R U R'",
    "x U R2 U L2 U' R2 U L2 U2 x'",
    "r U2 R2 F R F' R U' R' U' r' F R F'",
    "F U' L' U R2 U' L U R2 F'"
  ],
  "COLL-T5": [
    "R U R D R' U' R D' R2",
    "R U R' U R' D' R U' R' D R2 U' R'",
    "R' F' R U R' U' R' F R U R"
  ],
  "COLL-T6": [
    "R U R' U R U' L' R' U2 R U R' U2 L",
    "R2 U R' D' R U R' D R' U' R2 U' R2",
    "R U R' U R U' R' L' U2 R U R' U2 L",
    "L U' L2 D' l U2 l' D L2 U L'",
    "L' U2 L U' R' U L' U' R2 U' L U R'"
  ],
  "COLL-P1": [
    "R' U2 R2 U R2 U R2 U2 R'",
    "R U R' U R U2 R' U' R U R' U R U2 R'",
    "f R U R' U' f' F R U R' U' F'"
  ],
  "COLL-P2": [
    "R' F2 R U2 R U2 R' F2 U' R U' R'",
    "R U R' U R' F R2 U' R' U' R U R' F' U R U' R'",
    "U F U R U' R' U R U' R2 F' R U R U' R'",
    "R U' L' U R' U' L U' R U' L' U R' U' L",
    "R' U2 R U R' U' R U2 L U' R' U R L'"
  ],
  "COLL-P3": [
    "F' r U r' U' r' F r F R U R' U' F'",
    "R U2 R' U L' U2 R U R' U' R U' R' L"
  ],
  "COLL-P4": [
    "R U2 R' U' R U R' U2 L' U R U' R' L",
    "R B2 R' U2 R' U2 R B2 U R' U R",
    "R U R' U R U2 R' U' R U' L' U R' U' L"
  ],
  "COLL-P5": [
    "r U' r' U' r U r' U' x' R2 U' R' U R' x",
    "r U' r' U' r U r' F R' F' R2 U' R'",
    "R U' r' F R' F r U L' U L",
    "l F' r' x F l' U L U L' U L",
    "R U2 R' U' R U' R' L' U R U' L U R'",
    "R U' z U' R D' R U R U' R U z'"
  ],
  "COLL-P6": [
    "R2 D' R U R' D R U R U' R' U R U R' U R",
    "R U D' R U R' D R2 U' R' U' R2 U2 R",
    "R U2 R2 F R F' R' F R F' R' F R F' R U2 R'",
    "F R2 U' R U' R U' R' U2 R' U R2 F'",
    "r' U' R U' R' U R U' R' U R' F R F' U r",
    "R2 D' R U R' D R2 U' R' U R U' R' U2 R U2 R' U R",
    "U2 R U2 R' U R' D' R U R' D R2 U' R' U R U' R'",
    "F U R' U' R2 U' R2 U2 R F' L' U L",
    "R' U' D R' U' R D' R2 U R U R2 U2 R'",
    "R U' R' U2 L' U R U' L R' U2 R U R'"
  ],
  "COLL-H1": [
    "R' U' R U' R' U R U' R' U2 R",
    "L' U' L U' L' U L U' L' U2 L",
    "U' R' U2 R U R' U R U R U R' U R U2 R'",
    "U R U2 R' U' R U R' U' R U' R' U'",
    "L U L' U L U' L' U L U2 L'"
  ],
  "COLL-H2": [
    "f R U R' U' f' R U R' U' R' F R F'",
    "F R2 U' R2 U' R2 U R2 F' U S' U2 S",
    "R L' U' L U' L' U L U2 R' U L' U2 L"
  ],
  "COLL-H3": [
    "R U R' U R U r' F R' F' r",
    "R' F' R U2 R U2 R' F U' R U' R'",
    "R U R2 D' R U2 R' D R U' R U2 R'",
    "R' U' R U' R' U' L U' R U L'"
  ],
  "COLL-H4": [
    "U F R U R' U' R U R' U' R U R' U' F'",
    "R U' L' U R' U' L R U' L' U R' U' L",
    "R U' r' F R' F' r R U' r' F R' F' r",
    "r' F R F' r U r' R' F R F' r U R'",
    "y R U R' U y' R' U R U' R2 F R F' R"
  ],
  "2x2-oll-sune": [
    "R U R2 U' R2 U R",
    "R U' L' U R' U' L"
  ],
  "2x2-oll-anti-sune": [],
  "2x2-oll-pi": [
    "R U' R2 U R2 U R2 U' R",
    "R U2 R2 U' R2 U' R2 U2 R"
  ],
  "2x2-oll-p": [],
  "2x2-oll-l": [
    "F R U' R' U' R U R' F'",
    "F R' F' R U R U' R'"
  ],
  "2x2-oll-t": [
    "U R U R' U' F' U' F"
  ],
  "2x2-oll-h": [
    "R2 U2 R U2 R2",
    "F R U R' U' R U R' U' R U R' U' F'"
  ],
  "2x2-pbl-adj": [],
  "2x2-pbl-opp": [
    "F R U' R' U' R U R' F' R U R' U' R' F R F'"
  ],
  "2x2-pbl-opp-opp": [
    "R2 B2 R2"
  ],
  "2x2-pbl-adj-adj": [
    "R2 U R2 U2 F2 U F2"
  ],
  "2x2-pbl-adj-opp": [],
  "2x2-pbl-opp-adj": [],
  "CLL-AS-1": [
    "R' U' R U' R' U2 R",
    "U2 L' U' L U' L' U2 L",
    "U R U2 R' U' R U' R' U'"
  ],
  "CLL-AS-2": [
    "L' U' L U' L F' L' F L' U2 L",
    "U2 L' U' L U L F' L' F L' U L F' L F L' U'",
    "R U R' F' R U2 R' U' R U' R' F R U' R'",
    "U2 F L' U2 L U2 L F2 L' U' L' U L F"
  ],
  "CLL-AS-3": [
    "B' R B R' U2 R' U2 R"
  ],
  "CLL-AS-4": [
    "U2 L' U R U' L U R'"
  ],
  "CLL-AS-5": [],
  "CLL-AS-6": [
    "R2 F R U2 R U' R' U2 F' R",
    "R2 F' U' R2 F' R2 U F R2",
    "F R F' U R U' R U R' U R'",
    "y R U R' U y' R U' R U R' U R'",
    "y R U R' D R U' R U R' U R'",
    "L' U L' U L U' L U F' L F",
    "F U R' F' R U' F' U R' F R F'"
  ],
  "CLL-H-1": [
    "F R U' R' U R U2 R' U' R U R' U' F'",
    "y' R' U2 R y R' U R' U' R U' R",
    "R U2 R2 F R F' U2 R' F R F'"
  ],
  "CLL-H-2": [
    "R U R' U R U L' U R' U' L",
    "R' F' R U2 R U2 R' F U' R U' R'",
    "F R' F' R U2 F2 R U R' F U"
  ],
  "CLL-H-3": [
    "R U' R' F R' F' R2 U' R' F R' F' R",
    "R2 F' U2 F2 R2 F' R2",
    "R' F R F' R U R2 F R F' R U R'",
    "U F R U R' U' R U R' U' R U R' U' F'",
    "U' F U R U' R' U R U' R' U R U' R' F' U",
    "x R2 U' B2 U2 R2 U' R2 x'"
  ],
  "CLL-H-4": [
    "R U R' U R U' R' U R U2 R'",
    "U R2 U2 R' U2 R2 U",
    "U R2 U2 R U2 R2"
  ],
  "CLL-L-1": [
    "R' F' R U R' U' R' F R2 U' R' U2 R",
    "U' R U R' U R' F R F' U2 R' F R F'",
    "U' L' U L U' L' U L F' L F L2 U' L",
    "U' R' F R U' R' F R F' R U R2 F' R"
  ],
  "CLL-L-2": [
    "R U' R' U R U' R' F R' F' R2 U R'",
    "R' U2 R' U' F R2 F' U R2",
    "y R U2 R' U' y' R2 U' R' U R2",
    "R U R' U2 R U R' U F' U' F",
    "F R' U R F R' F' R U' R2 F'"
  ],
  "CLL-L-3": [
    "F U' R U' R' U R' F R F2",
    "R' F' R U' R' F R U' R' F R U' R' F2 R",
    "R U' R' L' U2 L U L' U L R U2 R'",
    "R U' R' L' U2 L U L' U L R U2 R' U2",
    "U R U R' U R U2 R' U2 R U2 R' U' R U' R'"
  ],
  "CLL-L-4": [
    "R U2 R' F R' F' R2 U2 R'"
  ],
  "CLL-L-5": [],
  "CLL-L-6": [
    "R U R U' R' F R' F'",
    "U x R' U R D' R' U' R D x'"
  ],
  "CLL-Pi-1": [
    "R' F2 R F' U2 R U' R' U' F",
    "U F U R U' R' U R U' R2 F' R U R U' R'",
    "F U' R' F2 R U' F2 R U2 R'",
    "L' U2 L F' U2 L F' L' U' F",
    "R' F2 R U2 R U2 R' F2 U' R U' R'"
  ],
  "CLL-Pi-2": [
    "R U R' U' R' F R2 U R' U' R U R' U' F'",
    "R2 U' R' U' F R2 U2 F' R2 F",
    "R U2 R' U2 R' F R2 U R' U' F'"
  ],
  "CLL-Pi-3": [
    "U' R' F R U F U' R U R' U' F'",
    "R' U' F' R U R' U' R' F R2 U2 R' U2 R",
    "F' R U R' U2 F' R U R2 F2 R",
    "y R' U R' U R U' R y' R' U2 R"
  ],
  "CLL-Pi-4": [
    "R U' R' F R' F R U R' F R",
    "R U' R' F L' U L U L' U L",
    "R U' R' F L' U L U R' F R",
    "R U' L' U R' U L U L' U L"
  ],
  "CLL-Pi-5": [
    "R2 U R' U' F R F' R U' R2",
    "U' R' U' R' F R F' R U' R' U2 R",
    "R U' R' U2 R' F R F' U2 R U R'",
    "R' F' U' F U' R U R' U R"
  ],
  "CLL-Pi-6": [
    "R U' R2 U R2 U R2 U' R",
    "R' U R2 U' R2 U' R2 U R'",
    "R U2 R2 U' R2 U' R2 U2 R",
    "R' U2 R2 U R2 U R2 U2 R'"
  ],
  "CLL-Sune-1": [
    "R' F2 R U2 R U' R' F",
    "R' F2 R U2 L F' L' F",
    "F U R U2 R' U' R U R' F'",
    "L' U2 L U2 R U' R' F"
  ],
  "CLL-Sune-2": [
    "R U2 R' F R U2 R' U R U' R' F",
    "R2 F' U' R2 F R2 U F R2",
    "y' R' U' R D' R' U R' U' R U' R"
  ],
  "CLL-Sune-3": [
    "R U' R' F L' U' L",
    "L F' L' F L' U' L",
    "R U' L' U R' U' L",
    "U2 R2 U R' U' R' F R F' R' U",
    "L F' L' F R' F' R"
  ],
  "CLL-Sune-4": [
    "F L' U' L U2 L F2 L'"
  ],
  "CLL-Sune-5": [
    "U2 R U R' U R' F R F' R U2 R'",
    "R U R' U' R' F R F' R U' R' F R' F' R",
    "x' R' F2 R U' R U R' x U R' U R",
    "L U' L' U L2 F' L' F L' U' L U L'",
    "R' F R F' U R U R' U2 F R' F' R"
  ],
  "CLL-Sune-6": [
    "R U R2 U' R2 U R"
  ],
  "CLL-T-1": [
    "U' x L U R' U' L' U R U' x'"
  ],
  "CLL-T-2": [],
  "CLL-T-3": [
    "R U' R' F2 U R U2 R' U F'",
    "R' U R2 D R' U2 R D' R2 U' R"
  ],
  "CLL-T-4": [
    "R U2 R' U' R U' R2 U2 R U R' U R",
    "F R' F R2 U' R' U' R U R' F2",
    "R U' R U' R U R' U R' U R'",
    "U' R U R' U R U2 R' U' R U2 R' U' R U' R' U'",
    "U' R U R' U R U2 R' U' R U2 R' U' R U' R'",
    "L' U2 L U L' U L U' L' U' L U' L' U2 L"
  ],
  "CLL-T-5": [
    "R U2 R' U R U2 R' U R' F R F'",
    "F R' U' R F' R' U F' R"
  ],
  "CLL-T-6": [
    "R' U R U2 L' R' U R U' L",
    "F R F' U R2 U' R U R2"
  ],
  "CLL-U-1": [
    "R' F' U' F U R"
  ],
  "CLL-U-2": [
    "R' F U' R U' R' U2 F2 R",
    "U' R U R' U' R U R' U' R' F R F' R' F R F' U2",
    "R U' R' F' L F' L' F2 U' R U R'"
  ],
  "CLL-U-3": [
    "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R",
    "F R U R' U' F R U R' U' F R U R' U'",
    "F' R U R' F U2 R U' R' F'",
    "U2 F R U R' U' R' U R U' F' U R' U' R"
  ],
  "CLL-U-4": [
    "F R U' R' U R U R' U R U' R' F'",
    "R2 F R F' R' F2 R U R' F R2",
    "F' L' U' L U' L' U' L U L' U L F U'"
  ],
  "CLL-U-5": [
    "R2 D' R U2 R' D R U2 R",
    "U2 R2 U R2 F' R U R U' R' F R U' R2",
    "R' U2 F R2 F' R2 F R2 F' R",
    "R' F R U' F U2 R U' R' U F'",
    "F U2 R U' R' U F' U' R' F R",
    "R' F R F' R U R' F U R U' R' F'",
    "R2 U' F R2 F' U R U2 R",
    "L U' L F' L' F L' U2 L U' L'"
  ],
  "CLL-U-6": [
    "L' U L2 F' L' F L' U' L U L' U' L",
    "R' F R2 U' R' F R' F' R U R' F' R",
    "R' U2 R U R2 F' R U R U' R' F R",
    "R U' R' U F' U2 R' F R U' F",
    "L2 D L' U2 L D' L' U2 L'",
    "U2 R2 D R' U2 R D' R' U2 R'"
  ],
  "EG1-AS-1": [],
  "EG1-AS-2": [
    "U2 L' U' L F2 U' F' L' U' L",
    "R U' F2 R U2 R U' F",
    "F R U' R' U R' F' R U F' R U R' U",
    "U F' L F L' F' L' U L U' L F L'"
  ],
  "EG1-AS-3": [
    "U' R U' R' U2 R' F R2 U2 R' F",
    "F' L F L' U' L F L2 U' L",
    "F' L F L' U' R U R' L' U' L"
  ],
  "EG1-AS-4": [
    "U F R U' R2 F' R U F' R U R'",
    "U' R' F R F' U R U' R2 F' R F",
    "U2 F U' L' U L U' F' L' U' L",
    "U F L F' L2 U' L U F' L F L'",
    "U' R U R' U2 R' F' R F R' F R"
  ],
  "EG1-AS-5": [],
  "EG1-AS-6": [],
  "EG1-H-1": [
    "U' R' F R2 U' R2 U' F U R",
    "F' R' F R F R' F' R2 U R'",
    "U R U' R2 F R F' R' F' R F",
    "F' R2 F' R F R' U R' U",
    "U' R' F R' F U F' R2 F'",
    "U R' F R2 U' R2 U' F U R"
  ],
  "EG1-H-2": [
    "F R U' R2 F U' F2 U R",
    "U R U' R' U' R U' R2 F2 R U R U R'",
    "U F' U R U' R2 F2 R U' F"
  ],
  "EG1-H-3": [
    "R' U' R' F2 U F' R F'",
    "U' F U2 R U' R' F2 R' F2 R F'"
  ],
  "EG1-H-4": [
    "F' U R' F R F' U F2",
    "U' R U R' F' R U R' U' R U R'",
    "R' F R F' R' F R U' R' F R F'",
    "F' U2 F' U R' F' R F'"
  ],
  "EG1-L-1": [],
  "EG1-L-2": [],
  "EG1-L-3": [],
  "EG1-L-4": [],
  "EG1-L-5": [],
  "EG1-L-6": [],
  "EG1-Pi-1": [
    "y2 R2 B2 R' U R' U' R U2 R U' R2",
    "U' R U' R2 F R2 U' R F2 R2 U'",
    "U' R' F R2 U' R2 F R' F2 R2"
  ],
  "EG1-Pi-2": [
    "y R' U R L U' L' R' U R"
  ],
  "EG1-Pi-3": [],
  "EG1-Pi-4": [],
  "EG1-Pi-5": [
    "U' R U R' U R U' R2 F' R F R' F' R",
    "R' U' R' F2 U' R U2 F2 R",
    "U' L F' L' F L F' L2 U' L U L' U L U'",
    "U' R U' R' F R U' R2 F' R U R' F R",
    "U2 F' L' U L F' L' U2 L U' F",
    "U F U' R U2 R' F' R U R' F'"
  ],
  "EG1-Pi-6": [
    "U' R' F R F' R' F R2 U R' U' R U' R'",
    "F R U' R' F R U2 R' U F'",
    "U' F R' F' R U R U R' U' R' F' R2 U R'",
    "U' L' U' L U' L' U L2 F L' F' L F L'"
  ],
  "EG1-S-1": [],
  "EG1-S-2": [
    "U F R' F' R F R U' R' U R' F' R",
    "U R' F R F U F2 R' F R"
  ],
  "EG1-S-3": [],
  "EG1-S-4": [
    "U F' R' F R2 U R' U' F R' F' R",
    "F' U R U' R' U F R U R'"
  ],
  "EG1-S-5": [],
  "EG1-S-6": [
    "L' U L2 F' L' U L F' L' F",
    "R' F R2 U' R' U L F' L' F"
  ],
  "EG1-T-1": [
    "F L F' L2 U' L U L' U' L",
    "U R2 U R U' R2 F R U2 R' F",
    "U2 R U2 R' U' R' F' R F R' F' R"
  ],
  "EG1-T-2": [
    "U2 R U2 R' F R U' R' F' R U R'",
    "U2 R U' R' F R U' R' F R U R' F'"
  ],
  "EG1-T-3": [],
  "EG1-T-4": [],
  "EG1-T-5": [],
  "EG1-T-6": [],
  "EG1-U-1": [
    "U2 R2 U' R' U' R U' R' U R'",
    "R U2 R U2 R U R2"
  ],
  "EG1-U-2": [
    "U' R U R' F' U' R U R' U' F R' F' R",
    "U' F R U' R' F U' F' R' F' R",
    "U F' R2 F' R2 F' U' F2 R2"
  ],
  "EG1-U-3": [
    "U2 R U' R2 F2 R F' U R U R'",
    "R U R' U F' R U R' U' R U R2 F2 R"
  ],
  "EG1-U-4": [],
  "EG1-U-5": [
    "U R' F R F' U R U' R' F R U' R'",
    "U2 L F' L' U L F' L' U L' U' L F",
    "F U' R' F2 R F' U2 F'",
    "F2 R U2 R' U' F2 U2 F'"
  ],
  "EG1-U-6": [],
  "EG2-AS-1": [
    "U2 R' U2 R2 U' R' U R' F R F R2",
    "x U' R2 F R2 F' U R' U2 R' U x'",
    "R U2 R' F R' F' R U' R U' R F2 R2",
    "U2 F R2 U2 R' U R' U2 R U' F'"
  ],
  "EG2-AS-2": [
    "U2 R' F' R U' R' F2 R' F2 R2",
    "R2 F2 R U' R U' R' U2 R"
  ],
  "EG2-AS-3": [
    "y2 L' U L F' R U R B2 R2"
  ],
  "EG2-AS-4": [],
  "EG2-AS-5": [
    "R' U' R U' R' U' R' F2 R F' R"
  ],
  "EG2-AS-6": [
    "R2 F2 R U L U' R U L'"
  ],
  "EG2-H-1": [
    "R U' R' F R' F' R2 U' R' F R' F' R' F2 R2",
    "U F R U R' U' R U R' U' R U R' U' F' R2 F2 R2 U'",
    "U x' U2 R U2 R2 F2 R' U2 x"
  ],
  "EG2-H-2": [
    "U R2 U2 R' U2 F2 R2"
  ],
  "EG2-H-3": [
    "U2 R U R' U R U R' F R' F' R' F2 R2",
    "R U' R2 U' F U' F U' R2 F R"
  ],
  "EG2-H-4": [
    "U2 F R2 U' R2 U' R2 U R2 F R2 F2 U'"
  ],
  "EG2-L-1": [],
  "EG2-L-2": [
    "y2 R2 B2 R' U R U' R' F R' F'",
    "U2 F' R U R' U' R' F R U R' F R' F2 R U' R"
  ],
  "EG2-L-3": [
    "U2 F' R U R' U' R' F2 R' F2 R U' R",
    "y2 R' U R' U2 R U' R' U R U' B2 R2"
  ],
  "EG2-L-4": [],
  "EG2-L-5": [],
  "EG2-L-6": [],
  "EG2-Pi-1": [
    "R' F' U' F U' R U R' U R' F2 R2 U'"
  ],
  "EG2-Pi-2": [
    "R U' R2 U R2 U R2 U' R' F2 R2",
    "R' U2 R2 U' R' F2 R2 F'",
    "R U2 R2 U' R2 U' R2 U2 R' F2 R2"
  ],
  "EG2-Pi-3": [],
  "EG2-Pi-4": [
    "U R U' F U' F' R F2 U2 R' U",
    "R U' R' F L' U L U R' F R' F2 R2",
    "R U' R' F R' F R U R' F R' F2 R2 U2"
  ],
  "EG2-Pi-5": [
    "U F U R U' R' U R U' R2 F' R U R U' R F2 R2 U'"
  ],
  "EG2-Pi-6": [
    "R U2 R' U' R U R' U2 R' F R F' R2 F2 R2",
    "R U R' U' R' F R2 U R' U' R U R' U' F R2 F2"
  ],
  "EG2-S-1": [
    "U' F U' R2 U' R' U2 R U' R2 F' U'"
  ],
  "EG2-S-2": [],
  "EG2-S-3": [
    "R U' R' F2 R2 F' L' U' L"
  ],
  "EG2-S-4": [],
  "EG2-S-5": [
    "R' F2 R U2 R U' R' F R2 F2 R2",
    "R U R' U R U R F2 R' U R'"
  ],
  "EG2-S-6": [
    "y2 R U' R U' R' U R' U' F R' F' R2 B2 R2"
  ],
  "EG2-T-1": [
    "U L' U' L U L F' L' F' R2 F2 U"
  ],
  "EG2-T-2": [
    "U F R' U2 R' U' R U2 F' U",
    "U' R U R' U' R' F R F R2 F2 U'"
  ],
  "EG2-T-3": [
    "R U2 R' U' R U' R2 U2 R U R' U R' F2 R2 U'",
    "y2 R' U R' U2 R U2 R' U R2 U' R B2 R2"
  ],
  "EG2-T-4": [
    "U R U2 R2 F R F' R U' R' U R U2 R F2 R2 U",
    "y2 R2 B2 R2 F R U R' U' F'",
    "F2 R2 F U' R' F R F",
    "F2 R2 F' R U R' U' F'"
  ],
  "EG2-T-5": [
    "R' U R U2 R2 F R F' R' F2 R2"
  ],
  "EG2-T-6": [
    "U R' U2 R' F2 R F2 R U",
    "U R' U' F R U2 R' U' F R",
    "U2 F R U R' U' R U' R' U' R U R' F R2 F2 U"
  ],
  "EG2-U-1": [
    "R' U' R U' R' U2 R2 U R' U R U2 R F2 R2 U'"
  ],
  "EG2-U-2": [],
  "EG2-U-3": [
    "R' F' R U R' U2 R U' R' F R",
    "F R U' R' U R U R' U R U' R' F R2 F2 U'"
  ],
  "EG2-U-4": [
    "F R U R' U' F R U R' U' F R U R F2 R2 U2"
  ],
  "EG2-U-5": [
    "R' U R' F R F' R U2 R' U R' F2 R2",
    "R' F R2 U' R' F R' F' R U R' F' R' F2 R2"
  ],
  "EG2-U-6": [
    "y2 R2 B2 R2 F R F' R U R' U' R'",
    "R U' R2 F R F' R U R' U' R U R F2 R2",
    "U2 R2 F2 R F' R U R U' R' F U2"
  ]
};
